const test=require('node:test'),assert=require('node:assert/strict'),m=require('../shared/accounting-confirmation-analysis'),base=require('../shared/finance-accounting-model');
test('one confirmation once with complete allocated and residual amounts',()=>{const r=m.query({view:'flows'});assert.equal(new Set(r.rows.map(r=>[r.source,r.entity,r.id].join('|'))).size,r.rows.length);for(const row of r.rows.filter(r=>r.amount!=null)){assert.equal(row.assigned+row.unassigned,row.amount);assert.equal(r.sections[0].rows.filter(p=>p.confirmation===row.id&&p.entity===row.entity&&p.source===row.source).reduce((n,r)=>n+r.amount,0),row.amount);}});
test('conflicting confirmations visible but not valid amounts',()=>{const r=m.query({view:'flows',scenario:'conflict'});assert.ok(r.rows.length);assert.equal(r.rows[0].amount,null);assert.match(r.rows[0].status,/冲突/);});
test('business settlement is not posted as income',()=>{const r=m.query({view:'flows',scenario:'missing'});assert.ok(r.rows.every(r=>['income','cost'].includes(r.kind)));const c=m.query({view:'completion',scenario:'missing'}).rows[0];assert.equal(c.businessRevenue,10000);assert.equal(c.income,null);assert.equal(m.columns.completion.includes('difference'),false);});
test('completion never truncates cumulative confirmation by hidden period',()=>{const a=m.query({view:'completion',scenario:'adjustment',periodEnd:'2026-05'}),b=m.query({view:'completion',scenario:'adjustment',periodEnd:'2026-06'});assert.deepEqual(a.rows.map(r=>r.cost),b.rows.map(r=>r.cost));});
test('confirmed period controls current postings and estimate reversal preserved',()=>{const r=m.query({view:'flows',scenario:'estimate'});assert.equal(r.rows.filter(r=>r.kind==='cost').reduce((n,r)=>n+r.amount,0),6200);assert.ok(r.rows.some(r=>r.estimate==='暂估冲回'));});
test('status filter applies to corresponding composition too',()=>{const r=m.query({view:'flows',status:'冲突'});assert.ok(r.rows.every(r=>r.status.includes('冲突')));assert.ok(r.sections[0].rows.every(p=>r.rows.some(r=>r.id===p.confirmation&&r.entity===p.entity)));});
test('order filter selects complete confirmation without unrelated unassigned ones',()=>{const d=base.fixture(),r=m.query({view:'flows',order:'RF-02A'},d);assert.ok(r.rows.length);assert.ok(r.rows.every(r=>r.orders.includes('RF-02A')));assert.equal(m.query({view:'flows',order:'不存在'}).rows.length,0);});
test('invalid date and missing source handled',()=>{assert.throws(()=>m.query({view:'completion',end:'2026-07-01'}));assert.equal(m.query({view:'flows',dataset:'pending'}).pending,true);});
