const test=require('node:test'),assert=require('node:assert/strict'),m=require('../shared/aging-clearing-analysis'),base=require('../shared/finance-balances-model');
test('aging ignores overdue mode and reconciles positive buckets',()=>{const r=m.aging({case:'BA01',ageBasis:'overdue'}).rows[0];assert.equal(r.b1,6000);assert.equal(r.b0,0);assert.equal(r.outstanding,6000);});
test('AP direction keeps prepayment offset and cash distinct',()=>{const r=m.aging({direction:'ap'});assert.equal(r.rows[0].outstanding,11000);assert.equal(r.sections[0].rows[0].offset,6000);});
test('missing due is not missing aging, missing history is not zero',()=>{assert.equal(m.aging({order:'YS-NODUE'}).rows[0].b1,5000);assert.equal(m.aging({case:'BA05'}).rows[0].outstanding,null);assert.equal(m.aging({order:'YS-ZERO'}).rows[0].outstanding,0);});
test('negative balances do not offset aging buckets; separate identities',()=>{const r=m.aging({order:'YS-REVERSE'}).rows[0];assert.equal(r.outstanding,0);assert.equal(r.reverse,-200);assert.equal(m.aging({case:'BA06',party:'阳光'}).rows.length,3);});
test('one row per paired relation and all constituent sides',()=>{const r=m.clearing();assert.equal(r.rows.length,4);assert.equal(r.sections[0].rows.length,6);const a=r.rows.find(r=>r.relation==='QS-AGENT-01');assert.equal(a.arBalance,5000);assert.equal(a.apBalance,5000);assert.equal(a.difference,0);});
test('company filter retains corresponding other company and no unrelated side',()=>{const r=m.clearing({company:'福建凯撒旅游'});assert.equal(r.rows.length,2);assert.equal(r.sections[0].rows.length,4);assert.equal(r.rows.find(r=>r.relation==='QS-PAY-01').arBalance,4000);});
test('unknown counterpart and mismatch are explicit',()=>{const s=base.fixture(),d=s.documents.find(d=>d.id==='QS-AGENT-01-AP');d.amount+=100;const a=m.clearing({},s).rows.find(r=>r.relation==='QS-AGENT-01');assert.equal(a.difference,-100);assert.equal(a.pairStatus,'双方余额有差异');const b=m.clearing().rows.find(r=>r.relation==='QS-UNKNOWN');assert.equal(b.apBalance,null);assert.equal(b.difference,null);});
test('historical coverage invalid dates and empty outcomes',()=>{for(const fn of [m.aging,m.clearing]){assert.throws(()=>fn({asOf:'2026-02-30'}));assert.equal(fn({asOf:'2027-01-01',cutoff:'2027-01-01T23:59'}).pending,true);assert.equal(fn({party:'无此单位'}).rows.length,0);}assert.equal(m.aging({case:'BA01',asOf:'2026-10-05'}).rows[0].outstanding,0);});
