const test=require('node:test'),assert=require('node:assert/strict');
const m=require('../shared/monthly-profit-model.js'),b=require('../shared/budget-targets.js'),s=require('../shared/supplier-report-model.js');
const q=(v={},d)=>m.query({dataset:'demo',...v},d);
test('默认待接入，不显示虚构利润',()=>assert.equal(m.query({}).pending,true));
test('核算公司收入成本费用与经营结果',()=>{const r=q().rows;assert.deepEqual(r.map(r=>[r.income,r.cost,r.expense,r.operating]),[[30000,24000,2600,3400],[24000,18000,600,5400]]);});
test('部门加未分配等于公司，管理结转不改公司总额',()=>{const r=q({view:'departments'});assert.equal(r.rows.filter(r=>r.company[0]==='A').reduce((a,r)=>a+r.operating,0),3400);assert.equal(r.rows.find(r=>r.department==='未分配费用').operating,-600);assert.equal(r.rows.reduce((a,r)=>a+r.transfer,0),0);});
test('已含优惠不重复扣，分配依据保留',()=>{const r=q({view:'expenses'}).rows;assert.equal(r.find(r=>r.id==='INCLUDED').impact,0);assert.equal(r.find(r=>r.id==='ADMIN').parts.length,3);});
test('费用缺失保持毛利但不出经营结果',()=>{const r=q({dataset:'gaps'}).rows[0];assert.equal(r.gross,6000);assert.equal(r.expense,null);assert.equal(r.operating,null);});
test('费用重传去重，冲突不计算',()=>{const d=m.fixture();d.expenses.push({...d.expenses[0]});assert.equal(q({},d).rows[0].expense,2600);d.expenses.at(-1).amount=999;assert.equal(q({},d).rows[0].operating,null);});
test('分配超额或未批准不计算',()=>{const d=m.fixture();d.expenses.find(r=>r.id==='ADMIN').allocations[0].amount=1000;assert.equal(q({},d).rows[0].operating,null);});
test('未知范围不产生合并结果',()=>{const r=q({view:'group'}).rows;assert.equal(r[0].income,54000);assert.equal(r[2].income,null);});
test('批准演示抵销只引用独立确认金额',()=>{const r=q({view:'group',groupScope:'demoApproved'}).rows;assert.deepEqual([r[1].income,r[1].cost,r[2].income,r[2].cost,r[2].operating],[-24000,-24000,30000,18000,8800]);assert.equal(q({view:'group',groupScope:'demoApproved',company:'A公司（演示）'}).rows[2].income,null);});
test('零负预算使用差额无误导完成率',()=>{const r=q({view:'budgets'}).rows;assert.equal(r[0].budget,0);assert.equal(r[0].variance,3400);assert.equal(r[2].budget,-100);assert.equal(r[2].variance,5500);assert.match(r[2].rate,/不适用/);assert.equal(q({view:'budgets',budgetVersion:'未接入'}).rows[0].budget,null);});
test('月度完整比较，不按天均摊预算',()=>assert.throws(()=>q({start:'2026-09-01'}),/月份/));
test('原发布版不被后补成本覆盖，次月返点只计一次',()=>{assert.equal(q().rows[1].cost,18000);assert.equal(q({version:'corrected'}).rows[1].cost,18500);assert.equal(q({start:'2026-10',end:'2026-10',version:'corrected'}).rows[1].cost,-300);assert.equal(q().rows[1].cost,18000);});
test('渠道同产品贡献和企业客户',()=>{const r=m.contribution({dataset:'demo',view:'channel',company:'A公司（演示）'});assert.deepEqual(r.rows.map(r=>r.contribution),[1900,1400,1600]);assert.equal(m.contribution({dataset:'demo',view:'channel',company:'A公司（演示）',customer:'科技'}).rows[0].contribution,1600);});
test('产品组合/供应/目的地共用相同收入成本',()=>{for(const grouping of ['product','supply','destination','type']){const r=m.contribution({dataset:'demo',grouping,company:'A公司（演示）'}).rows[0];assert.equal(r.income,30000);assert.equal(r.contribution,4900);}});
test('负毛利任务允许，订单任务仍非负',()=>{const r={...b.emptyTask(),name:'负毛利',scope:'product-group',metric:'margin',annual:'-1200',months:Array(12).fill('-100')};assert.equal(b.validate(r,[]),'');assert.equal(b.totals(r).annual,-120000);assert.equal(b.totals(r).difference,0);r.metric='orders';assert.notEqual(b.validate(r,[]),'');assert.equal(b.cents('-0.01',true),-1);});
test('供应商前十加其他等于完整采购，不用付款替代',()=>{const r=s.run();assert.equal(r.top.amount+r.other.amount,r.total.amount);assert.equal(r.total.amount,530000);const f=s.rebateFacts(s.rebates[0]);assert.deepEqual([f.confirmed,f.realized,f.allocated,f.unallocated],[10000,8000,9000,1000]);assert.equal(s.run({view:'allocations'}).rows.find(r=>r.id==='AL-01').costImpact,-6000);});
