const {test}=require('node:test'),assert=require('node:assert/strict');
const a=require('../shared/monthly-profit-analysis.js'),m=require('../shared/monthly-profit-model.js');
test('公司金额保持，补充不重复公司表',()=>{const r=a.query({view:'companies'});assert.deepEqual(r.rows,m.query({view:'companies'}).rows);assert.deepEqual(r.sections.map(s=>s.key),[]);});
test('部门直接/分配费用与公司费用、经营结果守恒',()=>{const r=a.query({view:'departments'}),companies=a.query({view:'companies'}).rows;for(const c of companies){const ds=r.rows.filter(d=>d.company===c.company);assert.equal(m.sum(ds.map(d=>d.directExpense+d.sharedExpense)),c.expense);assert.equal(m.sum(ds.map(d=>d.operating)),c.operating);assert.equal(m.sum(ds.map(d=>d.transfer)),0);}});
test('费用构成只按类别，旧部门分组参数不再改变主题',()=>{const r=a.query({view:'expenses'});assert.equal(m.sum(r.rows.map(e=>e.expense)),3200);assert.equal(r.sections[0].rows.length,7);assert.equal(r.sections[0].rows.find(e=>e.id==='INCLUDED').impact,0);assert.deepEqual(a.query({view:'expenses',expenseGrouping:'department'}),r);});
test('部门筛选费用记录只计当前分配',()=>{const r=a.query({view:'expenses',department:'直营'});assert.equal(m.sum(r.rows.map(e=>e.expense)),400);assert.equal(m.sum(r.sections[0].rows.map(e=>e.impact)),400);});
test('预算零负不算比例，费用少于预算为有利',()=>{const r=a.query({view:'budgets'});assert(r.rows.filter(x=>x.budget<=0).every(x=>x.varianceRate==='不适用'));assert.equal(r.rows.find(x=>x.metric==='经营费用'&&x.company.startsWith('A')).direction,'有利');});
test('集团未批准不当零，批准范围才形成调整后金额',()=>{assert(a.query({view:'group'}).rows.every(x=>x.adjustment===null&&x.after===null));const r=a.query({view:'group',groupScope:'demoApproved'});assert(r.rows.every(x=>x.before+x.adjustment===x.after));});
test('公司Tab忽略无关部门筛选，缺费用范围仍待补',()=>{assert.deepEqual(a.query({view:'companies',department:'不存在'}).rows,a.query({view:'companies'}).rows);assert(a.query({view:'companies',dataset:'gaps'}).rows.every(x=>x.operating===null));});

test('不同主题退出查看内容，内部调整独立且净额守恒',()=>{for(const view of ['companies','departments','budgets','approvedBudget'])assert.equal(a.query({view}).sections.length,0);const r=a.query({view:'management'});assert.equal(m.sum(r.rows.map(x=>x.transfer)),0);assert.equal(m.sum(r.sections[0].rows.map(x=>x.transfer)),0);});
test('部门费用独立主题明细与汇总承担一致',()=>{const r=a.query({view:'departmentExpenses'});for(const row of r.rows){const ds=r.sections[0].rows.filter(x=>x.company===row.company&&x.period===row.period&&x.currency===row.currency&&x.department===row.department);assert.equal(row.burden,m.sum(ds.map(x=>x.burden)));assert.equal(row.unassignedExpense,m.sum(ds.map(x=>x.unassignedExpense)));}});
test('集团调整明细逐项目与汇总调整对应',()=>{const r=a.query({view:'group',groupScope:'demoApproved'});for(const row of r.rows)assert.equal(row.adjustment,m.sum(r.sections[0].rows.filter(x=>x.metric===row.metric&&x.period===row.period&&x.currency===row.currency).map(x=>x.adjustment)));});
test('批准预算独立查询且不随实际后补成本变化',()=>{assert.deepEqual(a.query({view:'approvedBudget'}).rows,a.query({view:'approvedBudget',version:'corrected'}).rows);});
