const test=require('node:test'),assert=require('node:assert/strict'),M=require('../shared/predeposit-recharge-model.js'),C=require('../shared/predeposit-control-model.js');
function setup(){const accounts=C.seed(),pool=M.flows(),r=M.requests(accounts)[0];return {a:accounts[0],r,pool};}
const line=(amount,no='CMBC20260914001')=>({no,amount});
test('凭证提交不入账，必要付款资料校验',()=>{const {a}=setup(),before=a.ledger;assert.throws(()=>M.submit(null,{amount:'100',payer:'',payerAccount:'',receiving:'',paidAt:'',proof:''},a));const r=M.submit(null,{amount:'100',payer:a.name,payerAccount:'1234',receiving:'民生银行1234',paidAt:'2026-09-14',proof:'回单.png',remark:''},a);assert.equal(a.ledger,before);assert.equal(r.confirmed,0);});
test('订单认款与充值共同扣减可分配款',()=>{const {pool}=setup(),f=pool[0];assert.equal(M.remaining(f),2000000);M.use(f,'订单认款','order-2',1000000);M.use(f,'门店充值','charge-2',1000000);assert.equal(M.remaining(f),0);assert.throws(()=>M.use(f,'门店充值','charge-3',1));});
test('部分到账只增加已确认额，两流水完成同一申请',()=>{const {a,r,pool}=setup(),before=a.ledger;M.confirm(r,a,pool,[line('20000')],'2026-09-14','finance');assert.equal(r.status,'部分确认');assert.equal(a.ledger,before+20000);M.confirm(r,a,pool,[line('30000','CMBC20260914002')],'2026-09-14','finance');assert.equal(r.status,'已确认');assert.equal(a.ledger,before+50000);assert.equal(r.allocations.length,2);});
test('超额及多流水后项失败均不产生部分写入',()=>{const {a,r,pool}=setup(),before=JSON.stringify({a,r,pool});assert.throws(()=>M.confirm(r,a,pool,[line('20000'),line('30001','CMBC20260914002')],'2026-09-14','finance'));assert.equal(JSON.stringify({a,r,pool}),before);});
test('多到账只充申请额，余款保留',()=>{const {pool}=setup(),accounts=C.seed(),a=accounts[2],r=M.requests(accounts)[1];M.confirm(r,a,pool,[line('30000','CMBC20260914003')],'2026-09-14','finance');assert.equal(M.remaining(pool[2]),1000000);});
test('已完成不能重复确认',()=>{const {a,r,pool}=setup();M.confirm(r,a,pool,[line('20000'),line('30000','CMBC20260914002')],'2026-09-14','finance');const before=a.ledger;assert.throws(()=>M.confirm(r,a,pool,[line('1')],'2026-09-14','finance'));assert.equal(a.ledger,before);});
test('部分确认后退回保留已确认金额，原号补充重提',()=>{const {a,r,pool}=setup();M.confirm(r,a,pool,[line('10000')],'2026-09-14','finance');const balance=a.ledger,no=r.no;assert.throws(()=>M.sendBack(r,'','finance'));M.sendBack(r,'补清晰回单','finance');assert.equal(a.ledger,balance);assert.equal(r.confirmed,1000000);assert.throws(()=>M.confirm(r,a,pool,[line('1')],'2026-09-14','finance'));M.submit(r,{amount:'50000',payer:a.name,payerAccount:'1234',receiving:'民生银行',paidAt:'2026-09-14',proof:'清晰回单.pdf',remark:'补齐'},a);assert.equal(r.status,'部分确认');assert.equal(r.no,no);assert.equal(r.history.length,3);});
test('第三方付款必须核对归属及范围',()=>{const {a,r,pool}=setup(),l=line('1000','GDB20260625022');assert.throws(()=>M.confirm(r,a,pool,[l],'2026-09-14','finance'),/归属/);l.verified=true;assert.throws(()=>M.confirm(r,a,pool,[l],'2026-09-14','finance'),/依据/);l.basis='核对门店授权代付凭证';M.confirm(r,a,pool,[l],'2026-09-14','finance');assert.equal(r.confirmed,100000);});
test('公司和币种不能混用',()=>{const {a,r,pool}=setup();assert.throws(()=>M.confirm(r,a,pool,[line('1','CMB20260625018')],'2026-09-14','finance'),/公司/);pool[0].currency='美元';assert.throws(()=>M.confirm(r,a,pool,[line('1')],'2026-09-14','finance'),/币种/);});
test('整户限制、关闭及角色检查',()=>{const {a,r,pool}=setup();a.status='冻结';a.restrictions=['recharge'];assert.throws(()=>M.confirm(r,a,pool,[line('1')],'2026-09-14','finance'),/限制/);a.status='已关闭';assert.throws(()=>M.confirm(r,a,pool,[line('1')],'2026-09-14','finance'),/关闭/);a.status='正常';assert.throws(()=>M.confirm(r,a,pool,[line('1')],'2026-09-14','store'),/财务/);});
test('非法精度、负数、重复选择及倒签日期不能入账',()=>{for(const value of ['-1','0.001','NaN','Infinity'])assert.throws(()=>M.cents(value));const {a,r,pool}=setup();assert.throws(()=>M.confirm(r,a,pool,[line('1'),line('1')],'2026-09-14','finance'),/重复/);assert.throws(()=>M.confirm(r,a,pool,[line('1')],'2026-09-13','finance'),/早于/);});
test('重复流水不新增，真实同金额不同流水分别保留',()=>{const pool=M.flows(),before=pool.length;assert.equal(M.importFlow(pool,{...pool[0]}),false);assert.equal(pool.length,before);assert.equal(M.importFlow(pool,{...pool[0],no:'NEW-RECEIPT'}),true);assert.equal(pool.length,before+1);});
