const test=require('node:test');
const assert=require('node:assert/strict');
const M=require('../shared/sales-workbench-model.js');
function booking(s,extra={}){return {...M.quote(s,'sun',{productId:'sanya',slotId:'nov18',adults:2,children:0}),customerId:'C01',people:M.copy(s.customers[0].companions),mode:'已确认',accept:true,draftId:'sample',...extra};}
function setup(){const s=M.seed(),o=M.submitBooking(s,'sun',booking(s)),g=M.grant(s,'sun',o.id,'T1');return {s,o,g};}
const rejects=(f,phrase)=>assert.throws(f,new RegExp(phrase));
test('停用员工、非本人客户／订单及未授权产品均不可办理',()=>{const s=M.seed();rejects(()=>M.actor(s,'off'),'权限');rejects(()=>M.product(s,'sun','beijing'),'授权');rejects(()=>M.customer(s,'liu','C01'),'客户');rejects(()=>M.order(s,'liu',s.orders[0].id),'订单');});
test('客户按手机号复用，其他顾问名下号码不泄漏客户资料',()=>{const s=M.seed();assert.equal(M.saveCustomer(s,'sun',{name:'新名字',phone:'13900000001'}).id,'C01');rejects(()=>M.saveCustomer(s,'sun',{name:'某客户',phone:'13900000004'}),'转交');});
test('分享、咨询、意向与订单保留来源且重复接待不建第二份意向',()=>{const s=M.seed(),share=M.createShare(s,'sun',{productId:'sanya',kind:'intro'}),x=M.consult(s,share.id,{name:'赵宁',phone:'13900000006',consent:true,pax:2,note:'蜜月',date:'2026-11-18'});assert.equal(M.consult(s,share.id,{name:'赵宁',phone:x.phone,consent:true}).id,x.id);const i=M.acceptConsult(s,'sun',x.id);assert.equal(M.acceptConsult(s,'sun',x.id).id,i.id);assert.equal(i.shareId,share.id);const b=booking(s,{customerId:i.customerId,intentId:i.id,shareId:share.id}),o=M.submitBooking(s,'sun',b);assert.equal(o.sourceShare,share.id);assert.deepEqual(i.orders,[o.id]);assert.equal(i.stage,'已转订单');M.followIntent(s,'sun',i.id,'已核对需求',M.TODAY,false);assert.equal(i.stage,'已转订单');});
test('停用顾问的新增咨询转待分配',()=>{const s=M.seed(),x=M.createShare(s,'sun',{productId:'sanya'});s.staff[0].active=false;const c=M.consult(s,x.id,{name:'王雨',phone:'13900000008',consent:true});assert.equal(c.owner,null);assert.equal(c.status,'待分配');});
test('报价变化、过期和停售可明确判断',()=>{const s=M.seed(),x=M.createShare(s,'sun',{...booking(s),kind:'quote'});assert.equal(M.shareView(s,x.id).changed,false);s.products[0].revision++;assert.match(M.shareView(s,x.id).reason,/调整/);s.products[0].revision--;x.expires='2026-09-01';assert.match(M.shareView(s,x.id).reason,/过期/);s.products[0].active=false;assert.match(M.shareView(s,x.id).reason,/停售/);});
test('单房差及儿童占床价分别计算',()=>{const s=M.seed(),q=M.quote(s,'sun',{productId:'sanya',slotId:'nov18',adults:2,children:1});assert.equal(q.base,16000);assert.equal(q.supplement,1200);assert.equal(q.total,17200);rejects(()=>M.quote(s,'sun',{productId:'sanya',slotId:'nov18',adults:-1}),'人数');});
test('预订草稿不产生订单或名额占用，提交去重',()=>{const s=M.seed(),b=booking(s),stock=s.products[0].slots[0].stock,d=M.saveDraft(s,'sun',b);assert.equal(s.orders.length,1);assert.equal(s.products[0].slots[0].stock,stock);b.draftId=d.id;const o=M.submitBooking(s,'sun',b);assert.equal(M.submitBooking(s,'sun',b).id,o.id);assert.equal(s.orders.length,2);assert.equal(s.drafts.length,0);assert.equal(s.products[0].slots[0].stock,stock-2);});
test('价格、库存变化、缺游客和未核对条件禁止提交',()=>{const s=M.seed(),b=booking(s);s.products[0].price++;rejects(()=>M.submitBooking(s,'sun',b),'价格');s.products[0].price--;s.products[0].slots[0].stock=1;rejects(()=>M.submitBooking(s,'sun',b),'余位');s.products[0].slots[0].stock=8;rejects(()=>M.submitBooking(s,'sun',{...b,people:[]}), '人数');rejects(()=>M.submitBooking(s,'sun',{...b,accept:false}), '核对');});
test('条件未定只可待确认，不能转确认',()=>{const s=M.seed(),b=booking(s,{...M.quote(s,'sun',{productId:'sanya',slotId:'dec09',adults:2}),mode:'占位'});rejects(()=>M.submitBooking(s,'sun',b),'条件待确认');b.mode='待确认';const o=M.submitBooking(s,'sun',b);rejects(()=>M.confirmOrder(s,'sun',o.id),'条件待配置');});
test('二次确认需计调结果再由销售转确认',()=>{const s=M.seed(),b=booking(s,{...M.quote(s,'sun',{productId:'sanya',slotId:'dec02',adults:2})});rejects(()=>M.submitBooking(s,'sun',b),'计调');b.mode='待确认';const o=M.submitBooking(s,'sun',b);rejects(()=>M.confirmOrder(s,'sun',o.id),'资源尚未确认');M.demoResult(s,'sun',o.id,'resource','退回');rejects(()=>M.confirmOrder(s,'sun',o.id),'资源尚未确认');M.demoResult(s,'sun',o.id,'resource','通过');assert.equal(o.status,'待确认');M.confirmOrder(s,'sun',o.id);assert.equal(o.status,'已确认');});
test('纯占位可释放且恢复名额，已有资金时不直接释放',()=>{const s=M.seed(),o=M.submitBooking(s,'sun',booking(s,{mode:'占位'}));assert.equal(s.products[0].slots[0].stock,6);M.release(s,'sun',o.id);assert.equal(s.products[0].slots[0].stock,8);rejects(()=>M.release(s,'sun',o.id),'仅预留');const o2=M.submitBooking(s,'sun',booking(s,{mode:'预留',draftId:'second'})),g=M.grant(s,'sun',o2.id,'T1');M.pay(s,g.token,'T1');rejects(()=>M.release(s,'sun',o2.id),'款项');});
test('游客身份、入口用途、其他成人及失效入口限制',()=>{const {s,o,g}=setup();rejects(()=>M.verifyGuest(s,g.token,'13900000002','123456'),'不一致');rejects(()=>M.verifyGuest(s,g.token,'13900000001','000000'),'验证码');assert.equal(M.verifyGuest(s,g.token,'13900000001','123456'),'T1');rejects(()=>M.access(s,g.token,'T2','docs'),'其他游客');const docs=M.grant(s,'sun',o.id,'T2','docs');rejects(()=>M.access(s,docs.token,'T2','pay'),'不支持');const all=M.grant(s,'sun',o.id,'T2');rejects(()=>M.pay(s,all.token,'T2'),'联系人');g.enabled=false;rejects(()=>M.access(s,g.token),'失效');});
test('取消订单和旧合同版本入口失效',()=>{const {s,o,g}=setup();o.contract.version++;rejects(()=>M.access(s,g.token,'T1','sign'),'版本');o.status='已取消';rejects(()=>M.access(s,g.token),'无法继续');});
test('成功支付先定金后尾款，支付失败不增加已收',()=>{const {s,o,g}=setup();s.settings.payment='失败';M.pay(s,g.token,'T1');assert.equal(M.amounts(o).paid,0);s.settings.payment='成功';assert.equal(M.pay(s,g.token,'T1').amount,4000);assert.equal(M.pay(s,g.token,'T1').amount,8000);assert.equal(M.amounts(o).paid,12000);rejects(()=>M.pay(s,g.token,'T1'),'没有可再次支付');});
test('付款结果不明查询原笔，不再生成第二笔',()=>{const {s,o,g}=setup();s.settings.payment='结果未知';const p=M.pay(s,g.token,'T1');assert.equal(M.pay(s,g.token,'T1').id,p.id);assert.equal(o.payments.length,1);assert.equal(M.amounts(o).paid,0);assert.equal(M.amounts(o).inflight,4000);M.demoResult(s,'sun',o.id,'payment','通过');assert.equal(M.amounts(o).paid,4000);});
test('预确认款项记预收，不改变订单确认状态',()=>{const s=M.seed(),o=M.submitBooking(s,'sun',booking(s,{mode:'预留'})),g=M.grant(s,'sun',o.id,'T1'),p=M.pay(s,g.token,'T1');assert.equal(p.kind,'预收');assert.equal(o.status,'预留');});
test('原认款退回补充保留编号，复核前不计已收',()=>{const s=M.seed(),o=s.orders[0],prior=o.claims[0];rejects(()=>M.claim(s,'sun',o.id,prior,prior.id),'代付');const x=M.claim(s,'sun',o.id,{...prior,relation:'配偶代付'},prior.id);assert.equal(x.id,'RK-001');assert.equal(o.claims.length,1);assert.equal(M.amounts(o).paid,4000);assert.equal(M.amounts(o).pending,8000);assert.equal(M.amounts(o).available,0);M.demoResult(s,'sun',o.id,'claim','通过');assert.equal(M.amounts(o).paid,12000);assert.ok(x.history.length>=3);});
test('超额、重复流水及跨本人订单的重复认款被挡住',()=>{const {s,o}=setup(),v={amount:4000,payer:'李梅',reference:'ABC123',proof:'付款.jpg'};rejects(()=>M.claim(s,'sun',o.id,{...v,amount:13000}),'金额');M.claim(s,'sun',o.id,v);rejects(()=>M.claim(s,'sun',o.id,v),'已有认款');rejects(()=>M.claim(s,'liu',o.id,v),'订单');});
test('资料暂存、提交、退回、重新提交和核对通过分别处理',()=>{const {s,o,g}=setup(),v={name:'李梅',phone:'13900000001',identity:'DEMO-0001',emergency:'陈红',emergencyPhone:'13900000005'};M.material(s,g.token,'T1',{name:'李梅'},false);assert.equal(o.people[0].material.status,'暂存');rejects(()=>M.material(s,g.token,'T1',{name:'李梅'},true),'身份证');M.material(s,g.token,'T1',v,true);assert.equal(o.people[0].material.status,'待核对');rejects(()=>M.reviewMaterial(s,'sun',o.id,'T1',false,''),'退回原因');M.reviewMaterial(s,'sun',o.id,'T1',false,'联系人电话需核对');M.material(s,g.token,'T1',v,true);M.reviewMaterial(s,'sun',o.id,'T1',true);assert.equal(o.people[0].material.status,'已核对');assert.ok(o.people[0].material.history.length>=5);rejects(()=>M.material(s,g.token,'T1',v,true),'已核对');});
test('合同未确认、缺证件、未成年人监护关系均不得绕过',()=>{const {s,o}=setup();o.status='待确认';rejects(()=>M.prepareContract(s,'sun',o.id,true),'订单确认');o.status='已确认';o.people[1].identity='';rejects(()=>M.prepareContract(s,'sun',o.id,true),'待补');o.people[1].identity='DEMO-0002';o.children=1;rejects(()=>M.prepareContract(s,'sun',o.id,true),'监护');});
test('合同审核退回补正、受理未知查询、不重复发起',()=>{const {s,o,g}=setup();M.prepareContract(s,'sun',o.id,true);rejects(()=>M.sendContract(s,'sun',o.id),'尚未获准');M.demoResult(s,'sun',o.id,'contract','退回');assert.equal(o.contract.status,'审核退回');M.prepareContract(s,'sun',o.id,true);M.demoResult(s,'sun',o.id,'contract','通过');s.settings.contract='结果未知';M.sendContract(s,'sun',o.id);rejects(()=>M.sign(s,g.token,'T1',true),'尚不能签署');rejects(()=>M.sendContract(s,'sun',o.id),'尚未获准');M.demoResult(s,'sun',o.id,'contract','通过');M.sign(s,g.token,'T1',true);assert.equal(o.contract.status,'签署中');});
test('两位成人各自签署，加我方签章后才算完成',()=>{const {s,o,g}=setup(),g2=M.grant(s,'sun',o.id,'T2','sign');M.prepareContract(s,'sun',o.id,true);M.demoResult(s,'sun',o.id,'contract','通过');M.sendContract(s,'sun',o.id);rejects(()=>M.sign(s,g.token,'T1',false),'阅读');M.sign(s,g.token,'T1',true);assert.equal(o.contract.status,'签署中');M.sign(s,g2.token,'T2',true);assert.equal(o.contract.status,'签署中');M.demoResult(s,'sun',o.id,'seal','通过');assert.equal(o.contract.status,'已签署');});
test('签署资料变化先交顾问核对合同版本',()=>{const {s,o,g}=setup();M.prepareContract(s,'sun',o.id,true);rejects(()=>M.material(s,g.token,'T1',{name:'改名',phone:'13900000001',identity:'DEMO-0001'},false),'合同版本');});
test('出团通知发布与更新保留版本，未发布时为空',()=>{const {s,o}=setup();assert.equal(o.notice,null);M.demoResult(s,'sun',o.id,'notice','通过');assert.equal(o.notice.version,1);M.demoResult(s,'sun',o.id,'notice','通过');assert.equal(o.notice.version,2);});

test('付款安排未定不能提前发起收款',()=>{const s=M.seed(),o=M.submitBooking(s,'sun',booking(s,{...M.quote(s,'sun',{productId:'sanya',slotId:'dec09',adults:2}),mode:'待确认'})),g=M.grant(s,'sun',o.id,'T1');rejects(()=>M.pay(s,g.token,'T1'),'付款条件');assert.equal(o.payments.length,0);});
