const {test}=require('node:test'),assert=require('node:assert/strict');
const m=require('../shared/store-profit-model.js'),p=require('../shared/monthly-profit-model.js'),c=require('../shared/product-contribution-analysis.js');
const q=(input={},d)=>m.query(input,d),single=(r,id)=>r.sections[0].rows.find(r=>r.id===id);
test('分润基础、分配及公司留存；既有成本只引用不二次扣',()=>{const r=single(q(),'FR202609001');assert.equal(r.base,1000);assert.equal(r.storeShare,600);assert.equal(r.retained,400);assert.match(r.costReference,/不再扣减/);const report=c.query({view:'channel',company:'A公司（演示）'}),store=report.rows.find(x=>x.group==='加盟门店');assert.equal(store.fees,600);assert.equal(store.profitShare,600);assert.equal(store.contribution,1400);assert.equal(p.query({}).rows[0].operating,3400);});
test('缺规则、未批准、费用承担不明均待确认，不给正式分润',()=>{for(const id of ['FR202609003','FR202609004','FR202609005'])assert.equal(single(q(),id).storeShare,null);assert.equal(single(q(),'FR202609003').pendingAmount,500);assert.equal(single(q(),'FR202609005').pendingAmount,null);assert.equal(q().rows.find(r=>r.store==='软件园门店').storeShare,600);});
test('共同已含费用不重复扣；门店和公司专属费用分别承担',()=>{const d=m.fixture();let r=d.records[0];r.charges[0].included=true;assert.equal(single(q({},d),r.id).base,1100);r.charges[0].included=false;r.charges[0].bearer='门店';let out=single(q({},d),r.id);assert.equal(out.storeShare,560);assert.equal(out.retained,440);r.charges[0].bearer='公司';out=single(q({},d),r.id);assert.equal(out.storeShare,660);assert.equal(out.retained,340);});
test('升舱不是收入成本缺失兜底；排除毛利按规则，负基础不硬算',()=>{let d=m.fixture();d.records[0].upgradeRevenue=1500;assert.equal(single(q({},d),'FR202609001').base,500);d.records[0].upgradeCost=null;assert.equal(single(q({},d),'FR202609001').storeShare,null);d=m.fixture();d.records[0].cost=20000;assert.equal(single(q({},d),'FR202609001').storeShare,null);});
test('部分支付及抵扣、失败支付、逾期与未到期分开',()=>{const r=q({view:'execution'});let row=r.rows.find(x=>x.id==='FR202609001');assert.equal(row.payable,600);assert.equal(row.paid,200);assert.equal(row.offset,100);assert.equal(row.settled,300);assert.equal(row.remaining,300);assert.match(row.status,/已到期/);assert.equal(r.sections[0].rows.find(x=>x.id==='JF202609003').applied,0);assert.match(r.rows.find(x=>x.id==='FR202609002').status,/未到期/);});
test('确认退款调整入结果，未确认优惠不改原值，跨期重算按截止',()=>{let r=single(q(),'FR202609002');assert.equal(r.originalStore,1400);assert.equal(r.storeShare,1260);const before=single(q({cutoff:'2026-09-26'}),'FR202609002');assert.equal(before.storeShare,1400);assert.equal(single(q({cutoff:'2026-10-31'}),'FR202609002').storeShare,1330);let rows=q({view:'adjustments',start:'2026-10',end:'2026-10',cutoff:'2026-10-31'}).rows;assert.equal(rows.length,1);assert.equal(rows[0].period,'2026-09');assert.equal(rows[0].beforeStore,1260);assert.equal(rows[0].afterStore,1330);});
test('已确认调整增减不守恒或来源冲突时不冒充新结果',()=>{for(const mode of ['amount','conflict']){let d=m.fixture();if(mode==='amount')d.adjustments[0].deltaCompany=-1;else d.adjustments.push({...d.adjustments[0],deltaStore:-1});assert.equal(single(q({},d),'FR202609002').storeShare,null);}});
test('规则更版须有批准，调整保留旧版本并沿用新版本',()=>{let d=m.fixture();d.rules.push({...d.rules[1],id:'示例更正V3',rate:0.75});Object.assign(d.adjustments[0],{newRule:'示例更正V3',reason:'重结算规则更版',deltaBase:0,deltaStore:100,deltaCompany:-100});const row=q({view:'adjustments'},d).rows[0];assert.equal(row.rule,'示例规则V2');assert.equal(row.newRule,'示例更正V3');assert.equal(row.afterStore,1500);d.rules[3].approved=false;assert.equal(q({view:'adjustments'},d).rows[0].afterStore,null);});
test('超付显示待追回，成功追回减少支付净额',()=>{let d=m.fixture();d.executions[0].amount=700;let row=q({view:'execution'},d).rows[0];assert.equal(row.remaining,0);assert.equal(row.overpaid,200);d.executions.push({...d.executions[0],id:'RECOVER',kind:'追回',amount:200});row=q({view:'execution'},d).rows[0];assert.equal(row.difference,0);assert.equal(row.settled,600);});
test('原样重传去重，失败/成功冲突和无效结付不能当已结',()=>{let d=m.fixture();d.records.push(structuredClone(d.records[0]));d.executions.push(structuredClone(d.executions[0]));assert.equal(q({view:'execution'},d).rows[0].settled,300);d.executions.push({...d.executions[2],state:'成功'});assert.equal(q({view:'execution'},d).rows[0].settled,null);});
test('原记录缺失的结付及调整保留问题，不静默消失',()=>{let d=m.fixture();d.records=d.records.filter(r=>r.id!=='FR202609002');assert(q({view:'execution'},d).rows.some(r=>/缺失/.test(r.status)));assert(q({view:'adjustments'},d).rows.every(r=>/缺失/.test(r.status)));});
test('公司、门店、订单、原币及授权示例约束查询和明细',()=>{assert.equal(q({currency:'EUR'}).rows[0].storeShare,600);assert(q({scope:'channel'}).rows.every(r=>r.store==='软件园门店'));assert.equal(q({scope:'channel',company:'B公司（演示）'}).rows.length,0);assert.equal(q({scope:'company',store:'青岛'}).rows.length,0);assert.equal(q({order:'000002'}).sections[0].rows.length,1);assert.equal(q({store:'不存在'}).rows.length,0);});
test('无效日期、截止范围与权限类型拒绝；确认前保持待确认',()=>{for(const value of [{start:'2026-13'},{end:'2026-08'},{cutoff:'2026-02-30'},{cutoff:'2026-11-01'},{scope:'invalid'}])assert.throws(()=>q(value));assert.equal(single(q({cutoff:'2026-09-15'}),'FR202609001').storeShare,null);});
test('实际零分润与无规则区分；单条记录与公司留存核平',()=>{const d=m.fixture();d.records[0].revenue=10000;let r=single(q({},d),'FR202609001');assert.equal(r.base,0);assert.equal(r.storeShare,0);assert.equal(r.pendingCount,0);});

test('同一分润确认被两个费用号引用时不重复扣减',()=>{const d=p.fixture(),e=d.expenses.find(e=>e.profitShareId);d.expenses.push({...e,id:'重复费用号'});const r=c.query({view:'channel',company:'A公司（演示）'},d);assert(r.rows.every(r=>r.contribution===null));});
