const test=require('node:test'),assert=require('node:assert/strict'),m=require('../shared/supplier-prepayment-analysis'),base=require('../shared/finance-prepayments-model');
const q=(s,input={})=>m.query({party:'S1',currency:'CNY',...input},s);
function extra(s,props={}){const a=s.accounts.find(r=>r.id==='YF-001');s.accounts.push({...a,id:'YF-SECOND',opening:10000,openingAllocated:0,openingFrozen:0,openingReturn:0,since:'2026-09-01',returnDue:'',...props});}
test('supplier totals preserve balance, performance and overdue separately',()=>{const r=q().rows[0];assert.equal(r.closing,230000);assert.equal(r.unperformed,80000);assert.equal(r.overdueReturn,20000);assert.equal(r.longHeld,230000);assert.equal(q().sections[0].rows[0].allocated,200000);});
test('risk and supplier alias search retain complete account composition',()=>{const s=base.fixture();extra(s,{party:'另一名称'});for(const input of [{risk:'应退未退'},{party:'另一名称'}]){const r=q(s,input);assert.equal(r.rows[0].closing,240000);assert.equal(r.rows[0].accounts,2);assert.equal(r.sections[0].rows.length,2);assert.equal(r.rows[0].unperformed,null);}});
test('missing account invalidates aggregate instead of showing partial money',()=>{const s=base.fixture();extra(s,{history:false});const r=q(s).rows[0];assert.equal(r.closing,null);assert.equal(r.available,null);assert.equal(r.risk,'资料不足');assert.equal(r.accounts,2);});
test('company ledger currency and supplier identity cannot merge',()=>{const s=base.fixture();extra(s,{partyId:'OTHER'});extra(s,{company:'另一公司'});extra(s,{ledger:'另一账簿'});assert.equal(m.query({party:'远洋'},s).rows.length,5);});
test('duplicates are not double counted and conflicts remain unknown',()=>{const s=base.fixture();s.accounts.push({...s.accounts.find(r=>r.id==='YF-001')});assert.equal(q(s).rows[0].accounts,1);s.events.push({...s.events.find(r=>r.id==='CD-001'),amount:1});assert.equal(q(s).rows[0].closing,null);});
test('historical dates, zero, missing, empty and unsupported coverage stay distinct',()=>{assert.equal(q(undefined,{start:'2026-10-01',end:'2026-10-05'}).rows[0].closing,210000);assert.equal(m.query({party:'S3'}).rows[0].closing,0);assert.equal(m.query({party:'S2'}).rows[0].closing,null);assert.equal(m.query({party:'不存在'}).rows.length,0);assert.equal(m.query({end:'2026-11-01',cutoff:'2026-11-01'}).pending,true);for(const input of [{threshold:'-1'},{start:'2026-10-01'},{end:'2026-02-30'}])assert.throws(()=>m.query(input));});
