/* Independent mobile prototype. No remote model, payment, messaging or ERP requests. */
(() => {
'use strict';
const M=window.SalesModel, S=window.SalesSharing, KEY='caesar-sales-mobile-v2';
let state=M.seed(),storageOK=true;
try{const saved=JSON.parse(localStorage.getItem(KEY));if(saved?.schema===2&&saved.customers?.length&&saved.demands?.length&&Array.isArray(saved.orders))state=saved;}catch{storageOK=false;}
M.normalize(state);S.normalize(state);
const app=document.getElementById('app');
let customerView='customers',productFilters={from:'',to:'',budget:'',seats:false};
let route={name:'home'},stack=[],filter='全部',query='',productDeparture='全部',productSort='default',busy=new Set(),quoteExpired=false,dirty=false,toastTimer;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const d=()=>M.demand(state),c=id=>M.customer(state,id),p=()=>M.plan(d()),o=()=>state.orders.find(o=>o.id===route.id);
const paths={share:'<path d="M12 16V3m-4 4 4-4 4 4M6 11H3v10h18V11h-3"/>',home:'<path d="m3 10 9-7 9 7v10H4V10m5 10v-7h6v7"/>',users:'<circle cx="9" cy="8" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3m1-16a3 3 0 0 1 0 6m2 4a5 5 0 0 1 3 5"/>',spark:'<path d="m12 3 2.4 6.6L21 12l-6.6 2.4L12 21l-2.4-6.6L3 12l6.6-2.4L12 3Zm7-2 1 2.5L23 5l-3 1-1 3-1-3-3-1 3-1.5L19 1Z"/>',compass:'<circle cx="12" cy="12" r="9"/><path d="m16 8-2.5 5.5L8 16l2.5-5.5L16 8Z"/>',orders:'<rect x="5" y="4" width="14" height="17" rx="2"/><path d="M9 4V2h6v2m-6 6h6m-6 4h6m-6 4h3"/>',bell:'<path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/>',arrow:'<path d="m9 5 7 7-7 7"/>',back:'<path d="m14 5-7 7 7 7"/>',plus:'<path d="M12 5v14M5 12h14"/>',search:'<circle cx="10" cy="10" r="6.5"/><path d="m15 15 6 6"/>',check:'<path d="m5 12 4 4L20 5"/>',send:'<path d="m5 12 7-7 7 7M12 5v15"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/>',wallet:'<path d="M20 8V5H4v15h16V8ZM4 8h17v7h-6V9m2 3h.1"/>',file:'<path d="M14 3H5v18h14V8l-5-5v6h5M8 13h8m-8 4h5"/>',edit:'<path d="m15 3 6 6-11 11-7 1 1-7L15 3Zm-9 10 6 6m1-14 6 6"/>',plane:'<path d="m22 2-7 20-4-9L2 9l20-7ZM11 13 22 2"/>',shield:'<path d="m12 2 8 4v6c0 5-8 10-8 10S4 17 4 12V6l8-4Z"/><path d="m8 12 3 3 5-6"/>',download:'<path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/>',refresh:'<path d="M20 10a8 8 0 1 0 0 5m0-12v7h-7"/>',help:'<circle cx="12" cy="12" r="9"/><path d="M9 8a3 3 0 1 1 4 3c-1 .4-1 2-1 3m0 3h.01"/>'};
const icon=n=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${paths[n]||paths.file}</svg>`;
const btn=(text,action,cls='secondary',attrs='')=>`<button type="button" class="button ${cls}" data-action="${action}" ${attrs}>${text}</button>`;
const badge=(s,cls='')=>`<span class="tag ${cls}">${esc(s)}</span>`;
const customerLabel=id=>esc(c(id)?.name||'未选择客户');
const dates=x=>{if(!x)return '日期待定';const [y,m,day]=x.split('-');return esc((y==='2026'?'':y+'年')+Number(m)+'月'+Number(day)+'日');};
const party=x=>`${x.adults}成人${x.children?' · '+x.children+'儿童':''}`;
const back=title=>`<div class="subhead"><button class="back" data-action="back">${icon('back')}返回</button><h1>${title}</h1></div>`;
const field=(label,name,value='',type='text',attrs='')=>`<label class="field">${label}<input name="${name}" type="${type}" value="${esc(value)}" ${attrs}></label>`;
const select=(label,name,options,value)=>`<label class="field">${label}<select name="${name}">${options.map(x=>{const [v,t]=Array.isArray(x)?x:[x,x];return `<option value="${esc(v)}" ${String(v)===String(value)?'selected':''}>${esc(t)}</option>`;}).join('')}</select></label>`;
const textarea=(label,name,value='',attrs='')=>`<label class="field">${label}<textarea name="${name}" ${attrs}>${esc(value)}</textarea></label>`;
const errors=()=>'<div class="form-error" role="alert" id="form-error"></div>';
const empty=(title,subtitle,action='')=>`<div class="empty">${icon('compass')}<h3>${title}</h3><p>${subtitle}</p>${action}</div>`;
function save(){S.normalize(state);try{localStorage.setItem(KEY,JSON.stringify(state));storageOK=true;return true;}catch{storageOK=false;return false;} }
function toast(text){const el=document.getElementById('toast');el.textContent=text;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),3200);}
async function confirm(title,message){const dialog=document.getElementById('confirm-dialog');document.getElementById('confirm-title').textContent=title;document.getElementById('confirm-message').textContent=message;dialog.showModal();return new Promise(resolve=>dialog.addEventListener('close',()=>resolve(dialog.returnValue==='ok'),{once:true}));}
function navName(){if(['home','customers','assistant','products','orders'].includes(route.name))return route.name;if(['customer','new-customer','demand','new-demand','intent','follow-intent','close-intent'].includes(route.name))return 'customers';if(['product','booking','product-share','share-result','share-guest','share-consult','share-receive'].includes(route.name))return route.kind==='custom'?'assistant':'products';if(['plan','quote','compare','confirm-plan','preview','choose-demand'].includes(route.name))return 'assistant';if(['order','payment','claim','travelers','order-travelers','order-travel','order-aftersale','contract','contract-preview','aftersale','order-ai','success'].includes(route.name))return 'orders';return 'home';}
function render(){
  if(sharing.guestId&&!['share-guest','share-consult'].includes(route.name))route={name:'share-guest',sid:sharing.guestId};
  const titles={home:'工作台',customers:'客户',assistant:'AI助手',products:'产品',orders:'订单'};
  const root=Object.hasOwn(titles,route.name);
  document.title=(titles[navName()]||'销售')+' · 凯撒';
  const tabs=[['home','home','工作台'],['customers','users','客户'],['assistant','spark','AI助手'],['products','compass','产品'],['orders','orders','订单']];
  const header=root?`<header class="topbar mini-navigation"><span class="mini-brand" aria-hidden="true">CAISSA</span><h1>${titles[route.name]}</h1><span class="mini-capsule" aria-hidden="true"><span class="capsule-more"><i></i><i></i><i></i></span><span class="capsule-close"><i></i></span></span></header>`:'';
  app.className='app-shell '+(root?'root-view':'detail-view')+(route.name==='assistant'?' assistant-view':'');
  app.innerHTML=`${header}<main class="page page-${route.name} ${root?'':'page-detail'} ${route.name==='assistant'?'assistant-page':''}" id="main">${screens[route.name]?.()||home()}</main>${route.name==='assistant'?composer():''}${root?`<nav class="nav" aria-label="主导航">${tabs.map(([n,i,t])=>`<button data-nav="${n}" class="${navName()===n?'active':''}" ${navName()===n?'aria-current="page"':''}>${icon(i)}<span>${t}</span></button>`).join('')}</nav>`:''}`;
  const composerHeight=app.querySelector('.composer-wrap')?.getBoundingClientRect().height;
  if(composerHeight)document.documentElement.style.setProperty('--composer-height',composerHeight+'px');
  sharing.sync(app.querySelector('form[data-form="product-share"]'));
  dirty=false;
}
async function go(name,args={},replace=false){
  if(dirty && !(await confirm('离开当前编辑？','当前内容尚未保存，离开后将放弃本次修改。')))return;
  if(!replace)stack.push({...route,scroll:window.scrollY});route={name,...args};dirty=false;render();window.scrollTo(0,0);
}
async function returnToOrderPage(name){if(stack[stack.length-1]?.name===name&&stack[stack.length-1]?.id===route.id)stack.pop();await go(name,{id:route.id},true);}
async function goBack(){if(dirty&&!(await confirm('放弃未保存内容？','当前修改还未保存。')))return;route=stack.pop()||{name:'home'};dirty=false;render();window.scrollTo(0,route.scroll||0);}
function demandStatus(x){const pp=M.plan(x);return pp?.orderId?'已转订单':pp?.confirmation?'已确认':pp?.quote?'待客户确认':pp?'方案草稿':M.missing(x).length?'需求待补':'待规划';}
function home(){
 const pending=state.orders.flatMap(x=>{const list=[];const returned=x.claims.find(z=>z.status==='已退回');if(returned&&!x.claims.some(z=>z.status==='待复核'))list.push({o:x,title:'认款资料待补充',desc:customerLabel(x.customerId)+' · '+M.money(returned.amount),i:'wallet',time:'今天处理',tab:'payment',tone:'amber'});if(x.contract==='待签署')list.push({o:x,title:'合同等待客户签署',desc:customerLabel(x.customerId)+' · '+dates(x.date)+'出发',i:'file',time:'待签署',tab:'contract',tone:'sage'});return list;});
 const ongoing=state.demands.filter(x=>M.plan(x)&&!M.plan(x).orderId),recent=ongoing.find(x=>x.id===state.activeDemand)||ongoing[0];
 return `<section class="workspace-hero"><div class="workspace-identity"><button class="identity-person" data-action="profile" aria-label="林悦的账号"><span class="client-avatar" aria-hidden="true">悦</span><span><strong>林悦<span>销售顾问</span></strong><small>北京朝阳门店</small></span></button><button class="workspace-messages" data-action="notifications">${icon('bell')}<span>消息</span></button></div></section><div class="quick-grid"><button data-action="new-customer"><span class="quick-icon">${icon('users')}</span><span>接待客户</span></button><button data-nav="products"><span class="quick-icon">${icon('compass')}</span><span>找产品</span></button><button data-nav="assistant"><span class="quick-icon">${icon('spark')}</span><span>做方案</span></button><button data-action="quick-book"><span class="quick-icon">${icon('plus')}</span><span>快速开单</span></button></div><div class="section-head"><h2>优先处理 <span class="count">${pending.length}</span></h2><button class="link" data-action="notifications">全部 ${icon('arrow')}</button></div><div class="card task-list">${pending.length?pending.slice(0,3).map(t=>`<button class="task" data-action="open-order" data-id="${t.o.id}" data-tab="${t.tab}"><span class="task-symbol ${t.tone}">${icon(t.i)}</span><span class="task-content"><span class="task-title">${t.title}</span><span class="task-description">${t.desc}</span></span>${icon('arrow')}</button>`).join(''):'<div class="card-pad small">今天的优先事项已处理。</div>'}</div>${state.demands.some(x=>x.followAt&&x.followAt<=M.TODAY&&!['已关闭','已转订单'].includes(M.intentStage(x)))?`<div class="section-head"><h2>到期回访</h2></div><div class="card card-pad">${state.demands.filter(x=>x.followAt&&x.followAt<=M.TODAY&&!['已关闭','已转订单'].includes(M.intentStage(x))).map(x=>`<button class="list-row" data-action="intent" data-id="${x.id}"><span>${customerLabel(x.customerId)} · ${esc(x.destination)}<small class="muted"> · ${dates(x.followAt)}</small></span>${icon('arrow')}</button>`).join('')}</div>`:''}<div class="section-head"><h2>继续跟进</h2><button class="link" data-action="choose-demand">全部需求 ${icon('arrow')}</button></div>${recent?resumeCard(recent):empty('暂无进行中的方案','选择客户需求，开始规划。',btn('选择需求','choose-demand','soft'))}${state.bookingDraft?`<div class="card card-pad"><div class="row"><div><h3>开单草稿</h3><p class="small">${customerLabel(state.bookingDraft.customerId)} · 尚未提交</p></div>${btn('继续','resume-booking')}</div></div>`:''}<div class="month-summary"><span>${icon('wallet')} 本月已确认收款</span><strong>${M.money(state.orders.reduce((a,x)=>a+x.paid,0))}</strong></div><p class="workspace-footnote">林悦 · 本人业务 · 演示数据</p>`;
}
function resumeCard(x){const pp=M.plan(x);return `<div class="card resume-item"><div class="resume-top"><span class="client-avatar" aria-hidden="true">${customerLabel(x.customerId).slice(0,1)}</span><span class="resume-client"><strong>${customerLabel(x.customerId)}</strong><span>${esc(x.destination)} · ${x.days}日 · ${party(x)}</span></span>${badge(demandStatus(x),'orange')}</div><h3>${esc(pp?.title||x.destination+'出行需求')}</h3><p class="resume-note">${dates(x.date)}出发${pp?' · 第'+pp.version+'版':''} · ${pp?.quote?'已采用报价':'报价待核对'}</p><div class="resume-footer"><span class="small">${icon('spark')} AI方案已保存</span>${btn('继续方案 '+icon('arrow'),'use-demand','primary',`data-id="${x.id}"`)}</div></div>`;}
function searchBar(placeholder){return `<div class="search">${icon('search')}<input id="search" type="search" aria-label="${placeholder}" placeholder="${placeholder}" value="${esc(query)}" autocomplete="off"><button class="search-clear ${query?'':'is-hidden'}" data-action="clear-search" aria-label="清空搜索">×</button></div>`;}
function filterTabs(options){return `<div class="chips">${options.map(x=>{const label=Array.isArray(x)?x[0]:x,num=Array.isArray(x)?x[1]:null;return `<button data-filter="${label}" aria-pressed="${filter===label}" class="${filter===label?'active':''}">${label}${num!==null?`<span>${num}</span>`:''}</button>`;}).join('')}</div>`;}
function customerList(){return `<div class="list-toolbar"><div class="search-action-row">${searchBar(customerView==='intents'?'搜索客户、目的地或需求':'搜索姓名、手机号')}${btn(icon('plus')+' 新增客户','new-customer','toolbar-action')}</div><div class="segmented">${[['customers','我的客户'],['intents','出行意向']].map(([v,t])=>`<button data-action="customer-view" data-id="${v}" aria-pressed="${customerView===v}">${t}</button>`).join('')}</div>${filterTabs(customerView==='intents'?['全部','今日回访','新需求','跟进中','方案沟通','待成交','已转订单','已关闭']:['全部','有方案','待补需求'])}</div><div id="list-results">${customerResults()}</div>`;}
function customerResults(){if(customerView==='intents')return intentResults();const rows=state.customers.filter(x=>(x.name+x.phone).includes(query)&& (filter==='全部'||(filter==='有方案'?x.demands.some(id=>M.demand(state,id)?.plans.length):x.demands.some(id=>M.missing(M.demand(state,id)).length))));return `<div class="customer-list list-surface">${rows.map(x=>`<button class="customer-item" data-action="customer" data-id="${x.id}"><span class="client-avatar" aria-hidden="true">${esc(x.name.slice(0,1))}</span><span class="customer-info"><span class="row"><strong>${esc(x.name)}</strong><span class="customer-stage">${x.demands.length?demandStatus(M.demand(state,x.demands[0])):'暂无需求'}</span></span><span class="customer-phone">${esc(x.phone)}</span><span class="customer-context">${x.demands.length}次需求 · ${esc(x.demands.length?M.demand(state,x.demands[0])?.destination||'目的地待定':'待建立需求')}</span></span>${icon('arrow')}</button>`).join('')||empty('没有找到客户','调整搜索条件，或接待一位新客户。',btn('接待客户','new-customer'))}</div>`;}
function customerDetail(){const x=c(route.id);return back('客户详情')+`<div class="card card-pad customer-hero"><div class="row"><h1>${esc(x.name)}</h1>${badge(x.tag)}</div><p class="muted">${esc(x.phone)}</p><p class="small">${esc(x.note)}</p></div><div class="section-head"><h2>出行需求</h2><button class="link" data-action="new-demand" data-id="${x.id}">${icon('plus')}新需求</button></div>${x.demands.map(id=>demandCard(M.demand(state,id))).join('')}<div class="section-head"><h2>历史与当前订单</h2></div>${state.orders.filter(o=>o.customerId===x.id).map(orderCard).join('')||'<p class="small">暂无订单。</p>'}<div class="section-head"><h2>沟通记录</h2></div><div class="card card-pad">${state.notes.filter(n=>n.customerId===x.id).map(n=>`<p>${esc(n.text)}</p><small>${n.date}</small>`).join('')||'<p class="small">记录客户确认的偏好和沟通结果。</p>'}<form data-form="note">${textarea('补充记录','note')}${btn('保存记录','submit-form','secondary block')}</form></div>`;}
function demandCard(x,showOwner=false){return `<button class="card intent-row" data-action="intent" data-id="${x.id}"><span class="row"><strong>${showOwner?customerLabel(x.customerId):esc(x.destination||'目的地待定')+' · '+x.days+'日'}</strong>${badge(M.intentStage(x),x.stage==='已关闭'?'':'green')}</span>${showOwner?`<span class="intent-route">${esc(x.destination||'目的地待定')} · ${x.days}日</span>`:''}<span class="small">${intentDate(x)} · ${party(x)} · ${x.budget?M.money(x.budget):'预算待定'}</span><span class="small">${esc(x.preference||'偏好待补充')}</span><span class="intent-foot">${x.followAt&& !['已关闭','已转订单'].includes(M.intentStage(x))?'下次回访 '+dates(x.followAt):'查看需求与办理记录'} ${icon('arrow')}</span></button>`;}
function customerForm(){return back('接待客户')+`<form data-form="customer">${errors()}${field('客户姓名','name','')}${field('手机号码','phone','','tel','inputmode="tel" maxlength="11"')}${textarea('本次咨询摘要','note','','placeholder="如：11月亲子出游，预算3万元"')}${btn('保存并建立需求','submit-form','primary block')}</form>`;}
function demandForm(){const current=route.name==='new-demand'?{customerId:route.id,destination:'',departure:'北京',dateMode:'unknown',date:'',month:'',dateEnd:'',days:6,adults:2,children:0,childAge:null,budget:null,preference:'',source:'门店咨询',followAt:''}:M.demand(state,route.id);const x={...current,...(route.extracted||{})};return back(route.extracted?'核对提取结果':'出行需求')+`<div class="context"><div><h3>${customerLabel(x.customerId)}</h3><p class="small">${route.extracted?'只填写识别到的字段，核对后再保存':'一次出行，一份独立意向'}</p></div></div>${route.extracted?`<div class="hint gap">本地场景提取：标注“待核对”的字段来自沟通；未明确年份按演示年份2026预填，请核对。不会自动覆盖原需求。</div>`:''}<form data-form="demand">${errors()}${field('目的地','destination',x.destination,'text','placeholder="如：日本、三亚、欧洲"')}${field('出发城市','departure',x.departure)}${select('日期明确程度','dateMode',[['unknown','日期待定'],['month','只确定月份'],['range','日期范围'],['exact','具体日期']],x.dateMode)}<div data-date-fields="exact range" ${['exact','range'].includes(x.dateMode)?'':'hidden'}>${field('出发日期／范围开始','date',x.date,'date')}</div><div data-date-fields="range" ${x.dateMode==='range'?'':'hidden'}>${field('范围结束','dateEnd',x.dateEnd,'date')}</div><div data-date-fields="month" ${x.dateMode==='month'?'':'hidden'}>${field('出行月份','month',x.month,'month')}</div>${field('行程天数','days',x.days,'number','min="1" max="30"')}<div class="fields-two">${field('成人','adults',x.adults,'number','min="1" max="20"')}${field('儿童','children',x.children,'number','min="0" max="10"')}</div>${field('儿童年龄（可稍后补充）','childAge',x.childAge??'','number','min="0" max="17"')}${field('总预算（元，可留空待定）','budget',x.budget??'','number','min="1"')}${textarea('偏好与特别要求','preference',x.preference)}${select('客户来源','source',['门店咨询','微信咨询','电话咨询','官网留资','小程序咨询','老客推荐','其他'],x.source)}${field('下次回访日期（选填）','followAt',x.followAt,'date')}${route.extracted?`<div class="hint">待核对：${Object.keys(route.extracted).filter(k=>k!=='preference').map(k=>({destination:'目的地',departure:'出发城市',dateMode:'日期方式',date:'出发日期',month:'出行月份',days:'天数',adults:'成人',children:'儿童',childAge:'儿童年龄',budget:'预算'})[k]).filter(Boolean).join('、')||'未识别到明确字段，请手工填写'}。</div>`:''}${x.plans?.length?'<div class="hint gap">需求变化后保留历史方案；新需求需重新规划、核价与确认。</div>':''}${btn('保存需求','submit-form','primary block gap')}</form>`;}

function intentDate(x){return x.dateMode==='month'?esc(x.month.replace('-', '年'))+'月':x.dateMode==='range'?dates(x.date)+'—'+dates(x.dateEnd):dates(x.date);}
function intentResults(){const rows=state.demands.filter(x=>((c(x.customerId)?.name||'')+x.destination+x.preference).includes(query)&&(filter==='全部'||filter==='今日回访'&&x.followAt&&x.followAt<=M.TODAY&&!['已关闭','已转订单'].includes(M.intentStage(x))||filter===M.intentStage(x)));return `${rows.map(x=>demandCard(x,true)).join('')||empty('暂无符合条件的意向','调整筛选，或从客户详情创建本次出行需求。')}`;}
function intent(){const x=M.demand(state,route.id),stage=M.intentStage(x),closed=stage==='已关闭',converted=stage==='已转订单';return back('出行意向')+`<div class="card card-pad"><div class="row"><h2>${customerLabel(x.customerId)} · ${esc(x.destination)}</h2>${badge(stage,closed?'':'green')}</div><p class="small gap">${esc(x.departure||'出发地待定')}出发 · ${intentDate(x)} · ${x.days}日</p><p class="small">${party(x)} · ${x.budget?M.money(x.budget):'预算待定'} · ${esc(x.source)}</p><p class="gap">${esc(x.preference||'偏好待补充')}</p>${x.followAt&&!closed&&!converted?`<p class="small gap">下次回访 ${dates(x.followAt)}${x.followAt<M.TODAY?' · 已逾期':''}</p>`:''}${closed?`<div class="hint gap">关闭原因：${esc(x.closeReason)}</div>`:''}<div class="actions gap">${!closed&&!converted?btn('编辑需求','edit-demand','secondary',`data-id="${x.id}"`)+btn('记录跟进','follow-intent','primary',`data-id="${x.id}"`):closed?btn('恢复意向','reopen-intent','primary',`data-id="${x.id}"`):''}</div></div>${!closed&&!converted?`<div class="shortcuts"><button class="shortcut" data-action="intent-products" data-id="${x.id}">${icon('compass')}<b>找适合的产品</b><small>带入本次需求</small></button><button class="shortcut" data-action="use-demand" data-id="${x.id}">${icon('spark')}<b>AI整理与方案</b><small>继续当前会话</small></button></div>`:''}<div class="section-head"><h2>本次销售资料</h2></div><div class="card card-pad"><button class="list-row" data-action="candidates" data-id="${x.id}"><span>候选产品与对比</span><span>${x.candidates.length}项 ${icon('arrow')}</span></button>${x.plans.length?`<button class="list-row" data-action="use-demand" data-id="${x.id}"><span>方案与历史会话</span><span>${x.plans.length}版 ${icon('arrow')}</span></button>`:''}${state.bookingDraft?.demandId===x.id?btn('继续预订草稿','resume-booking','secondary block gap'):''}${[...new Set([...(x.orderIds||[]),...x.plans.map(p=>p.orderId).filter(Boolean)])].map(id=>btn('查看订单 '+id,'open-order','secondary block gap',`data-id="${id}"`)).join('')}</div><div class="section-head"><h2>跟进记录</h2></div><div class="card card-pad">${x.followups.length?x.followups.map(n=>`<p>${esc(n.text)}</p><p class="small">${esc(n.date)}${n.stage?' · '+esc(n.stage):''}${n.followAt?' · 下次回访 '+dates(n.followAt):''}</p><div class="divider"></div>`).join(''):'<p class="small">尚无本次需求的跟进记录。</p>'}</div>${!closed&&!converted?btn('关闭本次意向','close-intent','secondary block',`data-id="${x.id}"`):''}`;}
function followIntent(){const x=M.demand(state,route.id);return back('记录跟进')+`<form data-form="follow-intent">${errors()}${select('当前阶段','stage',M.stages,x.stage)}${textarea('本次沟通结果','text','','placeholder="记录客户反馈和下一步安排"')}${field('下次回访日期（选填）','followAt',x.followAt,'date',`min="${M.TODAY}"`)}${btn('保存跟进','submit-form','primary block')}</form>`;}
function closeIntent(){return back('关闭意向')+`<form data-form="close-intent">${errors()}${textarea('关闭原因','reason','','placeholder="如：客户暂缓出行"')}<p class="small gap">保留需求、方案与跟进历史，可在意向详情恢复。</p>${btn('确认关闭','submit-form','primary block gap')}</form>`;}
function extractDemandPage(){return back('AI整理需求')+`<p class="small gap">粘贴客户沟通，先核对提取结果，再保存到本次需求。</p><form data-form="extract-demand">${errors()}${textarea('客户沟通内容','text','','placeholder="例如：从北京出发，11月15日去日本6天，2大1小，孩子8岁，预算3万元，少换酒店。"')}<div class="hint">本地规则演示，仅识别明确的目的地、城市、日期、人数、年龄、天数与预算。其余内容保留为偏好，需销售核对。</div>${btn('提取并核对','submit-form','primary block gap')}</form>`;}
function candidates(){const x=M.demand(state,route.id);return back('候选产品对比')+`<div class="selection-context"><span>${customerLabel(x.customerId)} · ${intentDate(x)} · ${party(x)}</span></div><p class="small gap">参考总额按本次人数及儿童不占床计算，正式预订时核对规格。</p>${x.candidates.map(id=>{const p=M.products.find(p=>p.id===id);if(!p)return '';const m=M.productMatch(p,x);return `<div class="card card-pad"><h3>${esc(p.title)}</h3><p class="small">${p.departure}出发 · ${p.days}日 · ${p.type}</p><div class="row gap"><span>本次人数参考</span><strong>${M.money(m.total)}</strong></div><p class="small gap">${m.dates.length?'可选日期 '+m.dates.map(d=>dates(d.date)).join('、'):'当前需求范围暂无可售日期'}</p><p class="match-note">${m.issues.length?'需沟通：'+m.issues.join('、'):'符合当前日期范围、人数及预算条件'}</p><details class="gap"><summary>费用与退改差异</summary><p class="small">包含：${p.includes}</p><p class="small">不含：${p.excludes}</p><p class="small">${p.policy}</p></details><div class="actions gap">${btn('移出候选','candidate-remove','secondary',`data-id="${p.id}"`)}${btn('查看日期与预订','product','primary',`data-id="${p.id}" data-demand-id="${x.id}"`)}</div></div>`;}).join('')||empty('还没有候选产品','从产品详情将合适的线路加入本次候选。')}${!['已关闭','已转订单'].includes(M.intentStage(x))?btn('继续找产品','intent-products','secondary block',`data-id="${x.id}"`):''}`;}
function context(){const x=d();return `<div class="assistant-context"><div class="context-person"><span class="client-avatar" aria-hidden="true">${customerLabel(x.customerId).slice(0,1)}</span><div><h2>${customerLabel(x.customerId)}<span>${esc(x.destination)} · ${x.days}日</span></h2><p>${intentDate(x)} · ${party(x)}</p></div><button class="link" data-action="choose-demand">切换 ${icon('arrow')}</button></div><button class="context-plan" data-action="plan"><span>${icon('file')} 本次方案<span class="context-plan-status">${p()?'第'+p().version+'版 · '+demandStatus(x):'尚未生成'}</span></span>${icon('arrow')}</button></div>`;}
function assistant(){const x=d(),locked=['已关闭','已转订单'].includes(M.intentStage(x));return `${context()}<div class="assistant-tools" aria-label="AI快捷工具"><button class="shortcut" ${locked?'disabled':''} data-action="extract-demand" data-id="${x.id}">${icon('edit')}<span>整理需求</span></button><button class="shortcut" ${locked?'disabled':''} data-prompt="推荐适合的现成产品">${icon('compass')}<span>推荐产品</span></button><button class="shortcut" ${locked?'disabled':''} data-prompt="生成定制方案">${icon('plane')}<span>定制行程</span></button></div>${locked?`<div class="hint gap">${M.intentStage(x)}，保留历史会话。${btn('查看本次需求','intent','secondary',`data-id="${x.id}"`)}</div>`:''}${state.aiOffline?`<div class="hint warn gap">AI暂不可用，已保存的方案可以查看；产品预订和订单办理仍可直接使用。</div>`:''}<div id="messages">${x.messages.map(msg=>msg.role==='user'?`<div class="bubble-user">${esc(msg.text)}</div>`:`<div class="message">${msg.kind==='plan'?planCard(x,msg.version,msg.text):`<div class="assistant-copy">${assistantCopy(msg.text)}</div>${msg.kind==='products'?assistantProducts(x):msg.kind==='missing'?btn('补充出行需求','edit-demand','secondary',`data-id="${x.id}"`):''}`}</div>`).join('')}</div>${busy.has(x.id)?'<div class="busy" role="status" aria-label="正在整理方案"><i></i><i></i><i></i></div>':''}${x.plans.length?`<div class="luggage-chips"><button data-prompt="行程再轻松一点">行程再轻松一点</button><button data-action="compare">比较方案版本</button><button data-action="quote">查看报价与资源</button></div>`:''}`;}

function assistantCopy(text){const lines=String(text||'').split(/\n+/);return lines.map(line=>`<p>${esc(line)}</p>`).join('');}
function assistantProducts(x){const items=M.products.map(product=>({product,match:M.productMatch(product,x)})).sort((a,b)=>a.match.issues.length-b.match.issues.length);return `<section class="ai-recommendations" aria-label="为本次需求推荐的产品"><div class="ai-product-results" role="region" aria-label="推荐产品卡片">${items.map(({product:q,match})=>{const next=match.dates[0]||q.dates.find(z=>z.seats>0)||q.dates[0];return `<article class="ai-result-card"><div class="ai-card-heading"><div><span class="ai-kicker">产品推荐</span><h3>${esc(q.title)}</h3></div><span class="ai-stamp">${esc(q.type)}</span></div><p class="ai-card-summary">${esc(q.subtitle)} · ${esc(q.departure)}出发 · ${q.days}日</p><div class="ai-card-well"><div class="ai-value-row"><span>成人参考价</span><span>${M.money(q.adult)} / 人起</span></div><div class="ai-value-row"><span>${party(x)}</span><span>${next.seats?'余'+next.seats+'位':'已售罄'}</span></div><div class="ai-total-row"><span>本次人数参考总额</span><strong>${M.money(match.total)}</strong></div><p class="ai-card-meta">${dates(next.date)}出发${x.children?' · 儿童不占床':''}</p></div><p class="ai-match-note ${match.issues.length?'needs-check':''}">${match.issues.length?'需核对：'+esc(match.issues.join('、')):'符合当前日期、人数与预算条件'}</p>${btn('<span aria-hidden="true">→</span> 查看产品与可选日期','product','ai-card-action',`data-id="${q.id}" data-demand-id="${x.id}" data-date="${next.date}" aria-label="查看产品 ${esc(q.title)}"`)}</article>`;}).join('')}</div><p class="ai-result-note">参考价格以预订核对为准；差异项需与客户确认。</p>${btn('查看候选与对比','candidates','secondary block',`data-id="${x.id}"`)}</section>`;}

function composer(){return `<div class="composer-wrap"><form class="composer" data-form="chat"><label class="sr-only" for="message-input">告诉AI客户的想法</label><textarea id="message-input" name="message" rows="1" placeholder="补充需求，或调整方案…" ${busy.has(d().id)?'disabled':''}></textarea><button class="send" aria-label="发送消息" ${busy.has(d().id)?'disabled':''}>${icon('send')}</button></form></div>`;}
function dayList(pp,short=false){return `<div class="trip-days">${pp.days.slice(0,short?3:undefined).map((day,i)=>`<div class="day"><span class="day-no">${String(i+1).padStart(2,'0')}</span><div>${short?`<h3>${esc(day.title)}</h3><p>${esc(day.activity)}</p>`:`<details ${i===0?'open':''}><summary><span>${esc(day.title)}</span>${icon('arrow')}</summary><p>${esc(day.detail)}</p><div class="day-stay">${esc(day.stay)}<br>${esc(day.meal)}</div></details>`}</div></div>`).join('')}</div>`;}
function planCard(x,version,summary=''){const pp=version?x.plans.find(p=>p.version===version):M.plan(x);if(!pp)return '';return `<section class="ai-result-card ai-plan-card" aria-label="第${pp.version}版行程方案"><div class="ai-card-heading"><div><span class="ai-kicker">定制方案 · 第${pp.version}版</span><h3>${esc(pp.title)}</h3></div><span class="ai-stamp">${pp.quote?'已采用报价':'待核价'}</span></div>${summary?`<div class="ai-card-summary">${assistantCopy(summary)}</div>`:''}<div class="ai-card-well"><div class="ai-itinerary-lines">${pp.days.slice(0,3).map((day,i)=>`<details class="ai-day-detail"><summary><span>第${i+1}天</span><span>${esc(day.title)}</span>${icon('arrow')}</summary><div class="ai-day-expanded"><p>${esc(day.detail)}</p><p class="ai-card-meta">住宿 · ${esc(day.stay)}</p></div></details>`).join('')}</div><div class="ai-total-row"><span>${pp.quote?'已采用报价':'参考总价 · 待核价'}</span><strong>${M.money(pp.total)}</strong></div><p class="ai-card-meta">${intentDate(x)}出发 · ${party(x)}</p><p class="ai-card-meta">以上为前3天 · 完整方案共${pp.days.length}天</p></div>${btn('<span aria-hidden="true">→</span> 查看完整方案与报价','select-version','ai-card-action',`data-version="${pp.version}" aria-label="查看完整方案"`)}</section>`;}

function chooseDemand(){return back('选择客户与需求')+`<p class="small gap">选择本次出行，客户和人数会一同带入。</p>`+state.customers.map(x=>`<div class="section-head"><h2>${esc(x.name)}</h2></div>${x.demands.map(id=>{const z=M.demand(state,id),disabled=route.forProduct&&['已关闭','已转订单'].includes(M.intentStage(z));return `<button class="card intent-row" data-action="use-demand" data-id="${id}" ${disabled?'disabled':''}><span class="row"><strong>${esc(z.destination)} · ${z.days}日</strong>${badge(M.intentStage(z))}</span><span class="small">${intentDate(z)} · ${party(z)}</span></button>`;}).join('')}`).join('');}
function planPage(){const x=d(),pp=p();if(!pp)return back('本次方案')+empty('还没有方案','先补齐需求，或从产品中选择合适的线路。',btn('开始规划','assistant','primary'));return back('本次方案')+`<div class="receipt"><div class="row"><span class="eyebrow">本次方案</span>${badge(demandStatus(x),pp.confirmation?'green':'orange')}</div><h2>${esc(pp.title)}</h2><p class="small">${customerLabel(x.customerId)} · 第${pp.version}版 · ${dates(x.date)}</p><div class="perforation"></div><div class="row"><span>${party(x)}</span><span class="price">${M.money(pp.total)}</span></div><p class="small">${pp.quote?'采用报价 '+esc(pp.quote.id):'参考总价 · 尚未采用正式报价'}</p></div><div class="actions">${btn('版本比较','compare')}${btn('客户版预览','preview')}</div><div class="section-head"><h2>每日行程</h2><span class="small">点击展开</span></div><div class="card card-pad">${dayList(pp)}</div><div class="card card-pad"><h3>开单前核对</h3><button class="list-row" data-action="quote"><div>报价与资源<p>${pp.quote?'已采用有效报价 · 资源已确认':'待采用与本版对应的报价'}</p></div>${icon('arrow')}</button><button class="list-row" data-action="confirm-plan"><div>客户确认<p>${pp.confirmation?'已记录 · 第'+pp.version+'版':'尚未记录本版确认依据'}</p></div>${icon('arrow')}</button>${pp.orderId?`<button class="list-row" data-action="open-order" data-id="${pp.orderId}"><div>关联订单<p>${esc(pp.orderId)}</p></div>${icon('arrow')}</button>`:''}</div><div class="actions">${btn('继续修改','assistant')}${btn(pp.orderId?'查看订单':'核对开单',pp.orderId?'open-order':'custom-book','primary',pp.orderId?`data-id="${pp.orderId}"`:'')}</div>`;}
function compare(){const x=d();return back('方案版本')+`<p class="small">${customerLabel(x.customerId)} · 每次修改保留原版；开单采用选定版本。</p><div class="gap">${x.plans.slice().reverse().map(pp=>`<div class="card card-pad"><div class="row"><h3>第${pp.version}版</h3>${badge(pp.version===x.selected?'当前版本':pp.confirmation?'已确认版本':'历史草稿',pp.version===x.selected?'green':'')}</div><p>${esc(pp.change)}</p><div class="row gap"><span class="price">${M.money(pp.total)}</span><span class="small">${pp.quote?'报价已采用':'报价待采用'}</span></div><p class="small">${pp.confirmation?'客户确认：'+esc(pp.confirmation.evidence):'未记录客户确认'}</p>${pp.requestKey!==M.requestKey(x)?'<p class="small gap">历史需求版本，仅保留记录。</p>':pp.version!==x.selected?btn('查看此版本','select-version','secondary block gap',`data-version="${pp.version}"`):''}</div>`).join('')||empty('暂无方案版本','先生成一份方案。')}</div>`;}
function quote(){const pp=p(),x=d();if(!pp)return back('报价与资源')+empty('请先生成方案','目前没有可以对应的报价。');const q=M.quoteFor(x,pp,quoteExpired);return back('报价与资源')+`<div class="context"><div><h3>${customerLabel(x.customerId)} · 第${pp.version}版</h3><span class="small">${dates(x.date)} · ${party(x)}</span></div></div>${q?`<div class="card card-pad"><div class="row"><h3>产品组回复</h3>${badge(quoteExpired?'已过期':'有效报价',quoteExpired?'red':'green')}</div><p class="small">${q.owner} · 9月27日 10:30</p><p class="small">${q.id}</p><div class="divider"></div><p class="small">${q.scope}</p><div class="amount-lines gap">${q.items.map(item=>`<div class="row"><span>${item.name}</span><span>${M.money(item.amount)}</span></div>`).join('')}</div><div class="row quote-total"><strong>对客总价</strong><span class="price">${M.money(q.total)}</span></div><div class="divider"></div><div class="row small"><span>报价有效期</span><span>${q.validUntil}</span></div><div class="row small gap"><span>交通、住宿与门票</span><span>资源已确认</span></div></div><div class="hint">此为产品组已回复的演示记录。销售采用报价，资源确认由计调及产品岗位办理。</div>${btn('采用本版报价','adopt-quote','primary block gap',quoteExpired?'disabled':'')}${quoteExpired?'<p class="small gap">报价已失效，需重新核价后才能记录客户确认。</p>':''}`:`<div class="hint warn">当前日期、人数或行程没有对应的有效报价。请产品组核价后再采用；现阶段可以保留方案草稿。</div>`}`;}
function confirmPlanPage(){const pp=p();return back('记录客户确认')+(!pp?empty('暂无方案','先生成方案。'):`<div class="receipt"><div class="eyebrow">客户确认</div><h2>${esc(pp.title)}</h2><p>${customerLabel(d().customerId)} · 第${pp.version}版</p><p class="small">${dates(d().date)} · ${party(d())} · ${M.money(pp.total)}</p></div>${!pp.quote?`<div class="hint warn">请先采用本版有效报价，客户才能确认准确的行程与金额。</div>${btn('查看报价与资源','quote','primary block gap')}`:pp.confirmation?`<div class="card card-pad"><h3>已记录客户确认</h3><p>${esc(pp.confirmation.evidence)}</p><p class="small">${pp.confirmation.date}</p></div>${btn('核对开单','custom-book','primary block')}`:`<form data-form="confirm-plan">${errors()}${textarea('客户确认依据','evidence','','placeholder="如：9月27日客户微信确认第2版行程、人数及报价"')}<label class="check"><input type="checkbox" name="checked">我已向客户核对本版行程、日期、人数、费用与退改约定。</label>${btn('保存确认','submit-form','primary block')}</form>`}`);}
function preview(){const x=d(),pp=p();if(!pp)return back('客户版方案')+empty('暂无方案','先生成方案。');return `<div class="no-print">${back('客户版预览')}</div><article class="customer-preview"><div class="preview-head"><span class="eyebrow">CAISSA · MADE FOR YOU</span><h1 class="gap">${esc(pp.title)}</h1><p class="muted">为${customerLabel(x.customerId)}一家定制</p><p class="small">${dates(x.date)}出发 · ${party(x)} · 第${pp.version}版</p></div><img class="plan-cover gap" src="assets/kyoto.svg" alt="京都秋日景色"><div class="card gap"><div class="plan-head"><h3>慢一点，才看得见风景。</h3><p class="small">${esc(x.preference)}</p></div>${dayList(pp)}</div><div class="receipt"><div class="row"><span>${pp.quote?'旅行总价':'参考总价'}</span><span class="price">${M.money(pp.total)}</span></div><div class="divider"></div><h3>费用包含</h3><p class="small">往返经济舱交通、5晚家庭房及早餐、行程所列接送与当地交通、首道门票和服务。</p><h3 class="gap">费用不含</h3><p class="small">签证、未列明的餐食、个人消费和自选项目。</p><h3 class="gap">确认与退改</h3><p class="small">${pp.quote?'报价有效至'+pp.quote.validUntil+'；取消按合同约定核算实际损失。':'价格与资源尚待确认，本版为沟通草案。'}</p></div><p class="small center">凯撒旅游 · 北京朝阳门店<br>旅行顾问 林悦</p></article><div class="actions gap no-print">${btn('复制方案','copy-proposal')}${btn('记录客户确认','confirm-plan','primary')}</div>`;}
function productCards(compact=false){const demandId=compact?d().id:route.demandId,source=demandId?M.demand(state,demandId):null;let list=M.products.filter(x=>(x.title+x.subtitle+x.departure).includes(query)&&(filter==='全部'||filter===x.type)&&(productDeparture==='全部'||x.departure===productDeparture)&&(!productFilters.budget||x.adult<=Number(productFilters.budget))&&x.dates.some(z=>(!productFilters.from||z.date>=productFilters.from)&&(!productFilters.to||z.date<=productFilters.to)&&(!productFilters.seats||z.seats>0)));if(compact)list=M.products.slice().sort((a,b)=>M.productMatch(a,source).issues.length-M.productMatch(b,source).issues.length);else if(productSort==='price')list.sort((a,b)=>a.adult-b.adult);else if(productSort==='date')list.sort((a,b)=>(a.dates.find(x=>x.seats>0)?.date||'9999').localeCompare(b.dates.find(x=>x.seats>0)?.date||'9999'));const rows=list.map(x=>{const match=source?M.productMatch(x,source):null,available=compact?x.dates:x.dates.filter(z=>(!productFilters.from||z.date>=productFilters.from)&&(!productFilters.to||z.date<=productFilters.to)&&(!productFilters.seats||z.seats>0)),next=(match?.dates||[]).find(z=>available.includes(z))||available.find(z=>z.seats>0)||available[0];return `<div class="product-result"><button class="catalog-item" data-action="product" data-id="${x.id}" data-date="${next?.date||''}" ${demandId?`data-demand-id="${demandId}"`:''} aria-label="查看产品 ${esc(x.title)}"><img class="catalog-thumb" src="assets/${x.image}" alt=""><span class="catalog-info"><span class="catalog-title">${esc(x.title)}</span><span class="catalog-meta">${x.departure}出发 <i></i> ${x.days}日 <i></i> ${x.type}</span><span class="catalog-departure">${next?`${dates(next.date)}出发 <span class="seat-count">余${next.seats}位</span>`:'暂无可售团期'}</span><span class="catalog-footer"><span class="catalog-price">${M.money(x.adult)}<small>/成人起</small></span>${icon('arrow')}</span></span></button>${match?`<p class="match-note ${match.issues.length?'needs-check':''}">${match.issues.length?'需沟通：'+match.issues.join('、'):'符合当前日期范围、人数及预算条件'}<span>按本次人数参考 ${M.money(match.total)}${source.children?'（儿童不占床）':''}，以预订核对为准</span></p>`:''}</div>`;}).join('');return `${compact?'<p class="small gap">按当前需求排序；不匹配项明确标注，未替客户更改需求。</p>':''}<div class="catalog-list list-surface">${rows||empty('暂无匹配产品','试试其他日期、价格或出发城市。',btn('清空条件','reset-filter'))}</div>${compact?btn('查看候选与对比','candidates','secondary block gap',`data-id="${demandId}"`):''}`;}
function products(){const x=route.demandId&&M.demand(state,route.demandId);return `<div class="list-toolbar">${searchBar('搜索目的地、线路、出发城市')}${filterTabs(['全部','跟团游','自由行'])}<div class="product-filter-row"><div class="list-selects"><label><span aria-hidden="true">${productDeparture==='全部'?'全部出发地':productDeparture+'出发'}</span><select aria-label="出发城市" data-product-departure>${['全部','北京','上海'].map(x=>`<option value="${x}" ${productDeparture===x?'selected':''}>${x==='全部'?'全部出发地':x+'出发'}</option>`).join('')}</select>${icon('arrow')}</label><label><span aria-hidden="true">${({default:'默认排序',price:'价格从低到高',date:'最近出发'})[productSort]}</span><select aria-label="产品排序" data-product-sort>${[['default','默认排序'],['price','价格从低到高'],['date','最近出发']].map(([v,t])=>`<option value="${v}" ${productSort===v?'selected':''}>${t}</option>`).join('')}</select>${icon('arrow')}</label></div><details class="product-filter"><summary aria-label="日期、价格与余位筛选"><span>${Object.values(productFilters).some(Boolean)?'已筛选':'筛选'}</span>${icon('arrow')}</summary><form data-form="product-filter">${errors()}<div class="fields-two">${field('出发开始','from',productFilters.from,'date')}${field('出发结束','to',productFilters.to,'date')}</div>${field('成人单价上限（元）','budget',productFilters.budget,'number','min="1"')}<label class="check"><input type="checkbox" name="seats" ${productFilters.seats?'checked':''}>只看有余位</label>${btn('应用筛选','submit-form','secondary block')}</form></details></div></div>${x?btn('查看候选与对比','candidates','secondary block gap',`data-id="${x.id}"`):''}<div id="list-results">${productCards()}</div>`;}
function product(){const x=M.products.find(p=>p.id===route.id);const source=route.demandId&&M.demand(state,route.demandId),dt=x.dates.find(y=>y.date===route.date)||(source?M.productMatch(x,source).dates[0]:null)||x.dates[0];return back('产品详情')+`${source?`<div class="selection-context"><span>${customerLabel(source.customerId)} · ${intentDate(source)} · ${party(source)}</span></div>`:''}<div class="card"><div class="product-cover"><img src="assets/${x.image}" alt="${esc(x.subtitle)}旅行插画">${badge(x.type)}</div><div class="product-body"><span class="eyebrow">凯撒精选</span><h1 class="serif gap">${x.title}</h1><p class="product-meta">${x.departure}出发 · ${x.subtitle}</p><p>${x.description}</p></div></div>${source?`<div class="actions gap">${btn(source.candidates.includes(x.id)?'已加入候选':'加入本次候选','candidate-add','secondary',`data-id="${x.id}"`)}${btn('查看对比','candidates','secondary',`data-id="${source.id}"`)}</div>`:''}<div class="section-head"><h2>选择出发日期</h2></div><div class="date-grid">${x.dates.map(z=>`<button class="date-option ${dt.date===z.date?'active':''} ${z.seats===0?'sold':''}" data-action="select-date" data-date="${z.date}"><strong>${dates(z.date)}</strong><small>${z.seats?'余'+z.seats+'位 · '+z.mode:'已售罄 · 可换期'}</small></button>`).join('')}</div><div class="section-head"><h2>行程安排</h2><span class="small">已发布行程</span></div><div class="card card-pad">${x.itinerary.length?dayList({days:x.itinerary}):'<p class="small">苏黎世抵达 → 卢塞恩湖区 → 因特拉肯连住 → 少女峰地区 → 苏黎世返程。</p>'}</div><div class="card card-pad"><h3>费用包含</h3><p class="small">${x.includes}</p><h3 class="gap">费用不含</h3><p class="small">${x.excludes}</p><h3 class="gap">退改约定</h3><p class="small">${x.policy}</p></div><div class="sticky-actions product-detail-dock"><div class="row"><div><small>成人单价</small><div class="price">${M.money(x.adult)}</div></div>${btn(icon('share')+'分享','share-start','secondary product-share-button',`data-id="${x.id}" data-date="${route.date||''}" aria-label="分享产品"`)}${btn(dt.seats?'核对预订':'该团期已售罄','standard-book','primary',`data-id="${x.id}" data-date="${dt.date}" ${dt.seats?'':'disabled'}`)}</div></div>`;}
function booking(){const b=route.booking;const custom=b.kind==='custom',x=custom?M.plan(M.demand(state,b.demandId)):M.products.find(p=>p.id===b.productId),cust=c(b.customerId);return back('核对开单')+`<div class="receipt"><div class="eyebrow">预订信息</div><h2>${esc(x.title)}</h2><p class="small">${dates(b.date)} · ${custom?'客户确认方案 · 第'+b.version+'版':esc(x.departure)+'出发'}</p><div class="perforation"></div><div class="row"><span>${custom?'确认总价':'订单总额'}</span><span class="price" id="booking-total">${M.money(custom?x.total:M.standardTotal(b))}</span></div></div><form data-form="booking">${errors()}${b.demandId?`<div class="hint gap">本次需求：${customerLabel(b.customerId)} · ${esc(M.demand(state,b.demandId)?.destination||'')}。客户与需求绑定，需换客户请返回重新选择。</div><input type="hidden" name="customerId" value="${b.customerId}">`:select('下单客户','customerId',state.customers.map(c=>[c.id,c.name+' · '+c.phone]),b.customerId)}${field('联系人','contact',b.contact||cust?.name||'')}${field('联系电话','phone',b.phone||cust?.phone||'','tel','maxlength="11"')}<div class="fields-two">${field('成人','adults',b.adults,'number',`min="1" max="20" ${custom?'readonly':''}`)}${field('儿童','children',b.children,'number',`min="0" max="10" ${custom?'readonly':''}`)}</div>${!custom?`${field('儿童年龄（有儿童时必填）','childAge',b.childAge??'','number','min="2" max="11"')}${select('儿童规格','childBed',[['','请选择'],'不占床','占床'],b.childBed)}`:''}<div class="card card-pad"><div class="row small"><span>签约及收款公司</span><span>凯撒旅游北京公司</span></div><div class="divider"></div><p class="small">${custom?'提交后进入项目审核；通过后承接订单、合同及履约。':x.dates.find(z=>z.date===b.date)?.mode==='即时确认'?'本团期为即时确认，提交前核对余位和价格。':'本团期需二次确认，提交后由计调确认资源。'}</p></div>${!custom&&b.demandId&&!M.dateMatches(M.demand(state,b.demandId),b.date)?'<div class="hint warn gap">所选日期与原意向不同，请向客户核对本次实际出发日期。原需求记录保留。</div>':''}${custom?'':`<div class="hint">成人${M.money(x.adult)}；儿童不占床${M.money(x.child)}，占床另加${M.money(x.room)}。<br>${x.policy}</div>`}<label class="check"><input type="checkbox" name="accept" ${b.accept?'checked':''}>已核对客户、日期、人数、费用包含及退改约定。</label><div class="actions">${btn('保存草稿','save-booking')}${btn('提交订单','submit-form','primary')}</div></form>`;}
function orders(){return `<div class="list-toolbar">${searchBar('搜索客户、订单号或线路')}${filterTabs(['全部','已确认','待确认','预留','占位'])}</div>${state.bookingDraft?`<div class="draft-banner"><div>${icon('file')}<span>有一笔开单草稿<span class="small">${customerLabel(state.bookingDraft.customerId)} · 尚未提交</span></span></div>${btn('继续','resume-booking','soft')}</div>`:''}<div id="list-results">${orderResults()}</div>`;}
function orderResults(){const rows=state.orders.filter(x=>(x.title+x.id+(c(x.customerId)?.name||'')).includes(query)&&(filter==='全部'||filter===x.status));return `<div class="order-list">${rows.map(orderCard).join('')||empty('没有匹配的订单','换个关键词或状态试试。',btn('清空条件','reset-filter'))}</div>`;}
function orderCard(x){return `<button class="order-item" data-action="open-order" data-id="${x.id}" aria-label="查看订单 ${customerLabel(x.customerId)} ${esc(x.id)}"><span class="row order-item-head"><span class="order-customer"><span class="client-avatar" aria-hidden="true">${customerLabel(x.customerId).slice(0,1)}</span><strong>${customerLabel(x.customerId)}</strong></span>${badge(x.status,x.status==='已确认'?'green':'orange')}</span><span class="order-item-title">${esc(x.title)}</span><span class="order-facts"><span class="order-date-meta">${dates(x.date)}出发 · ${party(x)}</span><span class="order-item-amount"><small>${x.status==='已确认'?'应收':'预计'}</small><strong>${M.money(x.total)}</strong></span></span><span class="row order-item-foot"><span>${x.id}</span><span>查看详情 ${icon('arrow')}</span></span></button>`;}
function travelersTab(x){return `${x.travelers.map((t,i)=>`<div class="card card-pad"><div class="row"><h3>${esc(t.name||'游客'+(i+1))}</h3>${badge(M.travelerErrors(t,x.date).length?'资料待补':'已齐',M.travelerErrors(t,x.date).length?'orange':'green')}</div><p class="small">英文名 ${esc(t.english||'待填写')}</p><p class="small">证件 ${esc(t.passport? t.passport.slice(0,2)+'••••'+t.passport.slice(-2):'待补充')}</p>${btn('编辑资料','travelers','secondary block gap',`data-id="${x.id}" data-index="${i}"`)}</div>`).join('')}<div class="hint">证件有效期和签证要求需按目的地复核。资料交给计调与签证办理岗位承接。</div>`;}
function resourceTab(x){return `<div class="card card-pad"><div class="row"><h3>资源确认</h3>${badge(x.resource,x.resource==='已确认'?'green':'orange')}</div><p class="small">办理岗位：计调 · 周宁</p><div class="divider"></div>${['交通安排','酒店住宿','当地接送'].map(t=>`<div class="label-value row"><span>${t}</span><span>${x.resource==='已确认'?'已确认':'待回复'}</span></div>`).join('')}</div><div class="card card-pad"><h3>出团资料</h3><p class="small">出团通知尚未发布，发布后在本单查看。销售可查看结果，安排与调整由计调办理。</p></div>`;}
function travelerForm(){const x=o(),t=x.travelers[route.index];return back('游客资料')+`<form data-form="traveler">${errors()}${field('游客姓名','name',t.name)}${field('护照英文名','english',t.english,'text','placeholder="姓/名，如 LI/MEI"')}${field('护照号码','passport',t.passport)}${field('出生日期','birth',t.birth,'date',`max="${M.TODAY}"`)}${field('证件有效期至','expiry',t.expiry,'date')}<div class="hint">请逐项核对证件原件。此处为演示资料，请勿录入真实证件信息。</div>${btn('保存资料','submit-form','primary block gap')}</form>`;}
function orderAI(){const x=o(),pending=x.claims.some(z=>z.status==='待复核'),returned=x.claims.some(z=>z.status==='已退回');return back('AI看本单')+`<div class="context"><div><h3>${customerLabel(x.customerId)} · ${x.id}</h3><p class="small">基于当前订单信息整理</p></div>${badge('场景演示')}</div><div class="assistant-top">${icon('spark')} 凯撒 AI</div><h2 class="serif gap">这笔订单，下一步做什么？</h2><div class="card card-pad gap"><h3>${x.status==='待确认'?'先等待业务确认':pending?'认款已交财务复核':returned?'补充代付款关系依据':'核对合同与游客资料'}</h3><p>${x.status==='待确认'?'当前预计应收'+M.money(x.total)+'，订单尚未确认。请查看项目审核或资源回复结果。':pending?'新的认款资料已提交。等待财务核对到账，已确认收款仍为'+M.money(x.paid)+'。':returned?'原认款被退回，因为付款人与客户不一致。需要补充代付关系说明，再交财务核对，不需要让客户重复付款。':'当前合同为“'+x.contract+'”，请结合出发日期补齐资料并查看签署进度。'}</p></div><div class="card card-pad"><h3>给客户的回复草稿</h3><p class="small" id="reply-draft">${x.status==='待确认'?'您的预订需求已经提交，我们正在确认安排，收到结果后会及时与您核对。':pending?'您的付款资料已经提交复核，确认到账后我们会更新收款进度。':returned?'您好，您的付款凭证已收到。因为付款人姓名与订单联系人不一致，还需补充一下代付关系说明，我们会据此办理认款。':'您好，您的行程已经确认。请再核对游客资料和合同内容，签署完成后我们继续为您安排出行准备。'}</p>${btn('复制回复','copy-reply','secondary block gap')}</div>${btn('回到本单办理','open-order','primary block',`data-id="${x.id}"`)}`;}
function success(){const x=o();return back('提交结果')+`<div class="center gap-lg"><div class="success-mark">${icon('check')}</div><h1>订单已提交</h1><p class="muted">${x.status==='待确认'?'下一步由业务岗位确认。':'接下来可以办理合同、认款和游客资料。'}</p></div><div class="receipt gap-lg"><span class="eyebrow">订单摘要</span><h2>${esc(x.title)}</h2><p class="small">${x.id}</p><div class="perforation"></div><div class="row"><span>${customerLabel(x.customerId)} · ${party(x)}</span>${badge(x.status,x.status==='已确认'?'green':'orange')}</div><div class="row gap"><span>${dates(x.date)}</span><span class="price">${M.money(x.total)}</span></div></div>${btn('进入订单办理','open-order','primary block',`data-id="${x.id}"`)}<button class="button secondary block gap" data-nav="orders">返回订单列表</button>`;}
function profile(){return back('我的')+`<section class="profile-hero"><span class="eyebrow">销售档案</span><h1>林悦</h1><p>销售顾问 · 北京朝阳门店</p><p class="small">凯撒旅游北京公司</p></section><div class="card card-pad"><h3>原型演示</h3><p class="small">固定演示日期：2026年9月27日。AI回复为本地场景演示，业务动作只保存在当前浏览器，不发送真实订单、消息或合同。</p><div class="list-row"><div>AI暂不可用<small class="muted"> · 异常场景</small></div><button role="switch" aria-label="AI暂不可用" aria-checked="${state.aiOffline}" class="toggle ${state.aiOffline?'on':''}" data-action="toggle-offline"></button></div><div class="list-row"><div>报价已过期<small class="muted"> · 新采用时校验</small></div><button role="switch" aria-label="报价已过期" aria-checked="${quoteExpired}" class="toggle ${quoteExpired?'on':''}" data-action="toggle-expired"></button></div><button class="list-row" data-action="reset"><span>重置本项目演示数据</span>${icon('refresh')}</button></div><div class="hint">${storageOK?'草稿与办理记录保存在本浏览器，可关闭页面后继续。':'浏览器存储不可用，当前记录仅在本次打开期间保留。'}</div><p class="footer-note">CAISSA SALES MOBILE · 0.1.0</p>`;}
function notifications(){S.normalize(state);return back('消息与待办')+state.shareConsultations.filter(x=>x.status==='待接待').map(x=>`<div class="card card-pad"><div class="row"><h3>${esc(x.name)} · 产品咨询</h3>${badge('待接待')}</div><p class="small">${esc(M.products.find(p=>p.id===x.productId)?.title||'')} · ${x.pax}人</p>${btn('核对并接待','share-receive','secondary block gap',`data-id="${x.id}"`)}</div>`).join('')+state.orders.map(x=>`<div class="card card-pad"><div class="row"><h3>${customerLabel(x.customerId)} · 订单进展</h3>${badge(x.status)}</div><p class="small">${esc(x.logs[0])}</p>${btn('查看本单','open-order','secondary block gap',`data-id="${x.id}"`)}</div>`).join('');}
const sharing=window.createProductSharing({M,S,esc,icon,btn,badge,back,field,select,textarea,errors,empty,dayList,go,save,toast,confirm,state:()=>state,route:()=>route,clean:()=>{dirty=false;},render});
const orderPages=window.createOrderPages({M,esc,icon,btn,badge,back,field,select,textarea,errors,empty,dayList,order:o,customer:c,route:()=>route,travelersBody:travelersTab,travelBody:resourceTab});
const screens={...sharing.screens,...orderPages.screens,intent,'follow-intent':followIntent,'close-intent':closeIntent,'extract-demand':extractDemandPage,candidates,home,customers:customerList,customer:customerDetail,'new-customer':customerForm,demand:demandForm,'new-demand':demandForm,assistant,'choose-demand':chooseDemand,plan:planPage,compare,quote,'confirm-plan':confirmPlanPage,preview,products,product,booking,orders,travelers:travelerForm,'order-ai':orderAI,success,profile,notifications};
function bookingFromForm(form){const f=Object.fromEntries(new FormData(form));return {...route.booking,...f,adults:Number(f.adults),children:Number(f.children),accept:form.elements.accept.checked};}
function showError(form,message){const box=form.querySelector('.form-error');if(box){box.textContent=message;box.scrollIntoView({block:'center',behavior:'smooth'});}else toast(message);}
async function sendMessage(text){
 const x=d(),id=x.id;if(busy.has(id)||!text.trim())return;if(['已关闭','已转订单'].includes(M.intentStage(x))){toast('本次意向已结束，请恢复或建立新需求');return;}
 if(state.aiOffline){toast('AI暂不可用，请使用产品预订或人工编辑需求。');return;}
 x.messages.push({role:'user',text:text.trim()});busy.add(id);save();render();window.scrollTo(0,document.body.scrollHeight);
 setTimeout(()=>{
   let reply={role:'assistant',text:''};
   if(M.missing(x).length&&!/推荐|产品|现成|线路/.test(text)){reply.text='还需要确认'+M.missing(x).join('、')+'。补齐后，我再按准确的日期和人数推荐。';reply.kind='missing';}
   else if(/推荐|产品|现成|线路/.test(text)){reply.text='已按本次需求核对并排序。符合条件和需要沟通的差异分别列出，请再核对具体日期、规格和名额；没有合适产品时，可与客户沟通换期或调整需求。';reply.kind='products';}
   else if(/方案|行程|慢|轻松|换乘|京都|规划|定制/.test(text)&&x.destination==='日本'){
     try{const pp=M.revise(state,id);reply.text=`已保存第${pp.version}版：${pp.change} 原版保留在版本比较中；新版本需要重新采用报价并记录客户确认。`;reply.kind='plan';reply.version=pp.version;}catch(e){reply.text=e.message;reply.kind='missing';}
   } else if(/报价|价格|费用|预算/.test(text)){reply.text='请打开“报价与资源”查看与本版对应的产品组回复。参考总价不是已经确认的订单金额。';}
   else if(/确认|下单|开单/.test(text)){reply.text='可以从“本次方案”进入开单核对。需要先采用本版有效报价，并由销售记录客户确认依据；这条对话不会直接生成订单。';}
   else {reply.text='已保留这条需求。当前演示支持日本亲子方案编排、轻松版调整和现成产品推荐；其他具体要求可先在“编辑需求”中记录，再由业务完善方案。';reply.kind='missing';}
   x.messages.push(reply);busy.delete(id);save();if(route.name==='assistant'&&state.activeDemand===id){render();window.scrollTo(0,document.body.scrollHeight);}
 },650);
}
app.addEventListener('click',async ev=>{
 const el=ev.target.closest('button');if(!el||el.disabled)return;
 if(el.dataset.nav){filter='全部';query='';await go(el.dataset.nav,{},false);return;}
 if(el.dataset.filter){filter=el.dataset.filter;render();return;}
 if(el.dataset.prompt){await sendMessage(el.dataset.prompt);return;}
 const a=el.dataset.action,id=el.dataset.id;
 try{
  if(await sharing.action(a,el))return;
  switch(a){
   case 'back': await goBack();break;
   case 'submit-form': el.closest('form').requestSubmit();break;
   case 'clear-search':query='';render();document.getElementById('search')?.focus();break;
   case 'new-customer':await go('new-customer');break;
   case 'customer':await go('customer',{id});break;
   case 'customer-view':customerView=id;query='';filter='全部';render();break;
   case 'intent':case 'follow-intent':case 'close-intent':case 'extract-demand':case 'candidates':await go(a,{id});break;
   case 'reopen-intent':M.reopenDemand(M.demand(state,id));save();render();toast('意向已恢复');break;
   case 'intent-products':query='';filter='全部';productFilters={from:'',to:'',budget:'',seats:false};productDeparture='全部';await go('products',{demandId:id});break;
   case 'product-demand':await go('choose-demand',{forProduct:true});break;
   case 'candidate-add':{const x=M.demand(state,route.demandId);if(!x||['已关闭','已转订单'].includes(M.intentStage(x)))throw Error('请先选择进行中的客户需求');if(!x.candidates.includes(id)){if(x.candidates.length>=3)throw Error('最多对比3个产品，请先移除一个候选');x.candidates.push(id);}save();render();toast('已加入本次候选');break;}
   case 'candidate-remove':{const x=M.demand(state,route.id);x.candidates=x.candidates.filter(p=>p!==id);save();render();break;}
   case 'new-demand':await go('new-demand',{id});break;
   case 'edit-demand':await go('demand',{id});break;
   case 'choose-demand':await go('choose-demand');break;
   case 'use-demand':if(!M.demand(state,id))throw Error('需求不存在');if(route.forProduct){const target=route.productId?{name:'product',id:route.productId,date:route.date}: {name:'products'};await go(target.name,{...target,demandId:id},true);}else{state.activeDemand=id;save();await go('assistant');}break;
   case 'assistant':await go('assistant');break;
   case 'plan':await go('plan');break;
   case 'compare':await go('compare');break;
   case 'select-version':if(d().plans.find(p=>p.version===Number(el.dataset.version))?.requestKey!==M.requestKey(d()))throw Error('需求已经变化，请重新规划，历史版本仅供核对');d().selected=Number(el.dataset.version);save();await go('plan');break;
   case 'quote':await go('quote');break;
   case 'adopt-quote':M.adoptQuote(d(),p(),M.quoteFor(d(),p(),quoteExpired));save();toast('已采用本版报价');await go('plan',{},true);break;
   case 'confirm-plan':await go('confirm-plan');break;
   case 'preview':await go('preview');break;
   case 'copy-proposal':{const x=d(),pp=p();const value=[pp.title,'为'+c(x.customerId).name+'定制 · 第'+pp.version+'版',x.date+' · '+party(x),...pp.days.map((day,i)=>'第'+(i+1)+'天 '+day.title+'：'+day.detail), (pp.quote?'报价':'参考总价')+' '+M.money(pp.total), '费用包含：往返交通、5晚家庭房含早、行程所列交通门票与服务。','费用不含：签证、未列明餐食、个人消费及自选项目。',pp.quote?'报价有效至'+pp.quote.validUntil+'。取消按合同约定核算损失。':'价格与资源待确认，本版为沟通草案。'].join('\n');try{await navigator.clipboard.writeText(value);toast('客户版方案已复制');}catch{toast('复制受限，请使用客户版预览或保存文件');}break;}
   case 'product':await go('product',{id,date:el.dataset.date||'',demandId:el.dataset.demandId||route.demandId});break;
   case 'select-date':route.date=el.dataset.date;render();break;
   case 'quick-book':filter='全部';query='';await go('products');break;
   case 'standard-book':{if(!route.demandId){await go('choose-demand',{forProduct:true,productId:id,date:el.dataset.date});break;}const b=M.bookingFor(state,route.demandId,id,el.dataset.date);b.bookingId='B'+Date.now();await go('booking',{kind:'standard',booking:b});break;}
   case 'custom-book':{const x=d(),pp=p();if(!pp)throw Error('请先生成方案');if(pp.orderId){await go('order',{id:pp.orderId});break;}if(!pp.quote||!pp.confirmation){toast(!pp.quote?'先采用有效报价，再开单':'先记录本版客户确认');await go(!pp.quote?'quote':'confirm-plan');break;}const cust=c(x.customerId);await go('booking',{kind:'custom',booking:{kind:'custom',bookingId:'B'+Date.now(),demandId:x.id,version:pp.version,date:x.date,customerId:cust.id,contact:cust.name,phone:cust.phone,adults:x.adults,children:x.children,accept:false}});break;}
   case 'save-booking':state.bookingDraft=bookingFromForm(el.closest('form'));save();dirty=false;toast('开单草稿已保存');break;
   case 'resume-booking':if(state.bookingDraft)await go('booking',{kind:state.bookingDraft.kind,booking:M.clone(state.bookingDraft)});break;
   case 'open-order':await go(el.dataset.tab==='payment'?'payment':el.dataset.tab==='travelers'?'order-travelers':el.dataset.tab==='contract'?'contract':'order',{id});break;
   case 'order-page':if(['payment','contract','contract-preview','order-travelers','order-travel','order-aftersale'].includes(el.dataset.page))await go(el.dataset.page,{id});break;
   case 'claim-edit':await go('payment',{id,claimIndex:Number(el.dataset.index)},true);break;
   case 'claim':case 'contract':case 'aftersale':case 'order-ai':await go(a,{id});break;
   case 'travelers':await go('travelers',{id,index:Number(el.dataset.index)});break;
   case 'copy-reply':{const value=document.getElementById('reply-draft').textContent;try{await navigator.clipboard.writeText(value);toast('回复草稿已复制');}catch{toast('复制受限，请长按草稿选择复制');}break;}
   case 'reset-filter':productFilters={from:'',to:'',budget:'',seats:false};filter='全部';query='';productDeparture='全部';productSort='default';render();break;
   case 'profile':await go('profile');break;
   case 'notifications':await go('notifications');break;
   case 'toggle-offline':state.aiOffline=!state.aiOffline;save();render();break;
   case 'toggle-expired':quoteExpired=!quoteExpired;render();break;
   case 'reset':if(await confirm('重置演示数据？','仅清除本项目保存的客户、方案草稿和办理记录，恢复初始样例。')){state=M.seed();quoteExpired=false;stack=[];save();await go('home',{},true);toast('已恢复初始演示');}break;
  }
 }catch(error){toast(error.message);}
});
app.addEventListener('input',ev=>{
 sharing.sync(ev.target.closest('form'));
 const form=ev.target.closest('form');if(form&&!['chat','product-filter'].includes(form.dataset.form))dirty=true;
 if(ev.target.id==='message-input'){ev.target.style.height='auto';ev.target.style.height=Math.min(120,ev.target.scrollHeight)+'px';document.documentElement.style.setProperty('--composer-height',app.querySelector('.composer-wrap').getBoundingClientRect().height+'px');}
 if(ev.target.id==='search'){query=ev.target.value;app.querySelector('.search-clear')?.classList.toggle('is-hidden',!query);const box=document.getElementById('list-results');box.innerHTML=route.name==='customers'?customerResults():route.name==='products'?productCards():orderResults();}
 if(form?.dataset.form==='booking'){
  const b=bookingFromForm(form);document.getElementById('booking-total').textContent=M.money(b.kind==='custom'?M.plan(M.demand(state,b.demandId)).total:M.standardTotal(b));
 }
});
app.addEventListener('change',ev=>{
 sharing.sync(ev.target.closest('form'));
 if(ev.target.matches('[data-product-departure]')){productDeparture=ev.target.value;render();return;}
 if(ev.target.matches('[data-product-sort]')){productSort=ev.target.value;render();return;}
 const form=ev.target.closest('form');if(form&&!['chat','product-filter'].includes(form.dataset.form))dirty=true;
 if(form?.dataset.form==='demand'&&ev.target.name==='dateMode')form.querySelectorAll('[data-date-fields]').forEach(x=>x.hidden=!x.dataset.dateFields.split(' ').includes(ev.target.value));
 if(form?.dataset.form==='booking'&&ev.target.name==='customerId'){const cust=c(ev.target.value);form.elements.contact.value=cust.name;form.elements.phone.value=cust.phone;}
 if(form?.dataset.form==='aftersale'&&ev.target.name==='type'){document.getElementById('aftersale-fields').innerHTML=ev.target.value==='改期'?field('期望出发日期','date','','date',`min="${M.TODAY}"`):field('客户退款诉求金额（元）','amount','','number',`min="0.01" max="${o().paid}" step="0.01"`);}
});
app.addEventListener('submit',async ev=>{
 ev.preventDefault();const form=ev.target,f=Object.fromEntries(new FormData(form)),type=form.dataset.form;
 try{
  if(await sharing.submit(type,f,form))return;
  if(type==='chat'){await sendMessage(f.message||'');return;}
  if(type==='customer'){
   if(!f.name.trim()||!/^1\d{10}$/.test(f.phone))throw Error('请填写姓名和11位手机号码');
   if(state.customers.some(c=>c.phone===f.phone))throw Error('该手机号已有客户，请从客户列表查看');
   const id='c'+Date.now();state.customers.push({id,name:f.name.trim(),phone:f.phone,tag:'新客',note:f.note.trim(),demands:[]});save();dirty=false;await go('new-demand',{id},true);return;
  }

  if(type==='product-filter'){if(f.from&&f.to&&f.to<f.from)throw Error('结束日期不能早于开始日期');if(f.budget&&Number(f.budget)<=0)throw Error('价格上限须大于0');productFilters={from:f.from,to:f.to,budget:f.budget,seats:form.elements.seats.checked};render();return;}
  if(type==='follow-intent'){M.followDemand(M.demand(state,route.id),f);save();dirty=false;await go('intent',{id:route.id},true);toast('跟进已保存');return;}
  if(type==='close-intent'){M.closeDemand(M.demand(state,route.id),f.reason);save();dirty=false;await go('intent',{id:route.id},true);toast('意向已关闭');return;}
  if(type==='extract-demand'){if(!f.text.trim())throw Error('请先粘贴客户沟通');const patch=M.extractDemand(f.text);patch.preference=f.text.trim();dirty=false;await go('demand',{id:route.id,extracted:patch});return;}
  if(type==='demand'){
   const patch={destination:f.destination.trim(),departure:f.departure.trim(),dateMode:f.dateMode,date:f.date||'',dateEnd:f.dateEnd||'',month:f.month||'',days:Number(f.days),adults:Number(f.adults),children:Number(f.children),childAge:f.childAge===''?null:Number(f.childAge),budget:f.budget===''?null:Number(f.budget),preference:f.preference.trim(),source:f.source,followAt:f.followAt||''};
   const problems=M.validateDemand(patch);if(problems.length)throw Error(problems.join('；'));
   let x;if(route.name==='new-demand'){x={id:'d'+Date.now(),customerId:route.id,plans:[],selected:null,messages:[],stage:'新需求',followups:[],candidates:[],orderIds:[],...patch};M.updateDemand(x,patch);state.demands.push(x);c(route.id).demands.unshift(x.id);}else{x=M.demand(state,route.id);M.updateDemand(x,patch);}
   state.activeDemand=x.id;save();dirty=false;await go('intent',{id:x.id},true);toast('需求已保存');return;
  }
  if(type==='confirm-plan'){if(!form.elements.checked.checked)throw Error('请核对并勾选客户确认内容');M.confirmPlan(d(),p(),f.evidence);save();dirty=false;await go('plan',{},true);toast('已记录客户确认');return;}
  if(type==='booking'){
   const b=bookingFromForm(form);const problems=M.validateBooking(state,b);if(problems.length)throw Error(problems.join('；'));
   if(!(await confirm('提交这笔订单？',`${c(b.customerId).name} · ${b.date} · ${party(b)}。提交后进入${b.kind==='custom'?'项目审核':'订单办理'}。`)))return;
   const order=M.submitBooking(state,b);save();dirty=false;await go('success',{id:order.id},true);return;
  }
  if(type==='claim'){
   if(!f.date||f.date>M.TODAY)throw Error('请填写有效的付款日期');
   M.submitClaim(o(),{...f,claimIndex:form.dataset.claimIndex===''?undefined:Number(form.dataset.claimIndex),proof:f.proof?.name||'',customerName:c(o().customerId).name});save();dirty=false;await go('payment',{id:route.id},true);toast('已提交财务复核');return;
  }
  if(type==='traveler'){
   const t={name:f.name.trim(),english:f.english.trim().toUpperCase(),passport:f.passport.trim().toUpperCase(),expiry:f.expiry,birth:f.birth};const err=M.travelerErrors(t,o().date);if(err.length)throw Error(err.join('；'));o().travelers[route.index]=t;o().logs.unshift('已补充'+t.name+'游客资料。');save();dirty=false;await returnToOrderPage('order-travelers');toast('游客资料已保存');return;
  }
  if(type==='contract'){
   const x=o();if(x.status!=='已确认'||x.contract!=='未生成')throw Error('当前状态不能发起签署');if(x.travelers.some(t=>M.travelerErrors(t,x.date).length))throw Error('游客资料尚未齐全');if(!form.elements.checked.checked)throw Error('请先核对合同内容');x.contract='待签署';x.logs.unshift('已发起合同签署，等待客户签署结果。');save();dirty=false;await go('contract',{id:route.id},true);toast('已发起签署（演示）');return;
  }
  if(type==='aftersale'){M.submitAftersale(o(),f);save();dirty=false;await go('order-aftersale',{id:route.id},true);toast('售后申请已提交');return;}
  if(type==='note'){if(!f.note.trim())throw Error('请填写沟通记录');state.notes.unshift({customerId:route.id,text:f.note.trim(),date:'2026-09-27'});save();dirty=false;render();toast('已保存沟通记录');}
 }catch(error){showError(form,error.message);}
});
window.addEventListener('beforeunload',ev=>{if(dirty){ev.preventDefault();ev.returnValue='';}});
// VisualViewport keeps the composer above the mobile keyboard without moving the page shell.
if(window.visualViewport){const update=()=>{const inset=Math.max(0,window.innerHeight-window.visualViewport.height-window.visualViewport.offsetTop);document.documentElement.style.setProperty('--keyboard',inset>100?Math.max(0,inset-(app.querySelector('.nav')?.getBoundingClientRect().height||0))+'px':'0px');};window.visualViewport.addEventListener('resize',update);window.visualViewport.addEventListener('scroll',update);}
window.addEventListener('storage',event=>{if(event.key===KEY&&event.newValue){try{const fresh=JSON.parse(event.newValue);if(fresh.schema===2&&fresh.customers?.length&&fresh.demands?.length){state=fresh;M.normalize(state);S.normalize(state);if(!dirty)render();}}catch{}}});
if(sharing.guestId)route={name:'share-guest',sid:sharing.guestId};
render();
})();
