/* Order handling pages: sales actions remain separate from finance and fulfillment. */
window.createOrderPages=function(env){
  const {M,esc:e,icon,btn,badge,back,field,select,textarea,errors,empty,dayList}=env;
  const order=()=>env.order(),customer=()=>env.customer(order().customerId);
  const pending=x=>x.claims.filter(z=>z.status==='待复核').reduce((n,z)=>n+z.amount,0);
  const available=x=>Math.max(0,x.total-x.paid-pending(x));
  const product=x=>M.products.find(p=>p.id===x.productId||p.title===x.title);
  const contractName=x=>product(x)?.id==='p2'?'团队境内旅游合同':'团队出境旅游合同';
  const section=t=>`<div class="section-head"><h2>${t}</h2></div>`;
  const facts=rows=>`<dl class="order-facts-list">${rows.map(([k,v])=>`<div><dt>${k}</dt><dd>${v}</dd></div>`).join('')}</dl>`;
  const context=x=>`<div class="order-context"><strong>${e(customer()?.name||'订单客户')}</strong><span>${e(x.id)}</span><p>${e(x.title)} · ${e(x.date)}出发</p></div>`;
  const entry=(x,title,note,screen,i)=>`<button class="order-handle-row" data-action="order-page" data-page="${screen}" data-id="${x.id}"><span class="order-handle-icon">${icon(i)}</span><span class="order-handle-text"><strong>${title}</strong><small>${e(note)}</small></span>${icon('arrow')}</button>`;
  function detail(){const x=order();if(!x)return back('订单详情')+empty('订单不存在','请返回订单列表。');const missing=x.travelers.filter(t=>M.travelerErrors(t,x.date).length).length;
    return back('订单详情')+`<section class="card card-pad order-summary"><div class="row"><span class="small">${e(x.id)}</span>${badge(x.status,x.status==='已确认'?'green':'orange')}</div><h1>${e(x.title)}</h1><p class="small">${e(customer()?.name)} · ${x.date}出发 · ${x.adults}成人${x.children?' · '+x.children+'儿童':''}</p><div class="order-money-grid"><div><span>${x.status==='已确认'?'订单应收':'预计金额'}</span><strong>${M.money(x.total)}</strong></div><div><span>已确认收款</span><strong>${M.money(x.paid)}</strong></div><div><span>${x.status==='已确认'?'待收金额':'待确认金额'}</span><strong>${M.money(x.total-x.paid)}</strong></div></div>${pending(x)?`<div class="hint">认款 ${M.money(pending(x))} 待财务复核，未计入已确认收款。</div>`:''}${x.status==='待确认'?`<div class="hint warn">${x.kind==='custom'?'单团项目待审核':'资源待计调确认'}，当前金额仅为预计。</div>`:''}</section>${section('本单办理')}<div class="card order-handle-list">${entry(x,'收款与认款',pending(x)?'待财务复核 '+M.money(pending(x)):x.claims.some(z=>z.status==='已退回')?'认款退回 · 待补充资料':'待收 '+M.money(x.total-x.paid),'payment','wallet')}${entry(x,'合同办理',x.contract,'contract','file')}${entry(x,'游客资料',(x.travelers.length-missing)+'/'+x.travelers.length+'人资料已齐','order-travelers','users')}${entry(x,'出行资料',x.notice?'出团通知已发布':'资源'+x.resource+' · 出团通知待发布','order-travel','plane')}${entry(x,'售后办理',x.aftersales.length?x.aftersales.length+'条申请 · '+x.aftersales[x.aftersales.length-1].status:'改期、退订及申请进度','order-aftersale','shield')}</div>${btn(icon('spark')+' AI帮我看本单','order-ai','soft block',`data-id="${x.id}"`)}${section('订单信息')}<div class="card card-pad">${facts([['联系人',e(customer()?.name)],['联系手机',e(customer()?.phone||'待补充')],['签约及收款公司',e(x.company)],['销售顾问','林悦'],['预订类型',x.kind==='custom'?'定制方案':'标准产品']])}</div>${section('办理记录')}<div class="card card-pad"><ul class="timeline">${x.logs.map(l=>`<li>${e(l)}</li>`).join('')}</ul></div>`;
  }
  function payment(){const x=order(),prior=Number.isInteger(env.route().claimIndex)?x.claims[env.route().claimIndex]:null,editing=prior?.status==='已退回';return back('收款与认款')+context(x)+`<div class="card card-pad">${facts([['收款公司',e(x.company)],['已确认收款',M.money(x.paid)],['认款待复核',M.money(pending(x))],['可新认领金额',M.money(available(x))]])}</div>${section('认款记录')}${x.claims.map((z,i)=>`<div class="card card-pad"><div class="row"><strong>${M.money(z.amount)}</strong>${badge(z.status,z.status==='已退回'?'red':z.status==='已确认'?'green':'orange')}</div><p class="small gap">付款人 ${e(z.payer)} · ${e(z.reference)}</p>${z.reason?`<div class="hint warn">退回原因：${e(z.reason)}</div>`:''}${z.history?.length?`<details class="order-record-history"><summary>办理记录</summary><ul class="timeline">${z.history.map(h=>`<li>${e(h)}</li>`).join('')}</ul></details>`:''}${z.status==='已退回'&&x.status==='已确认'?btn('补充原申请','claim-edit','secondary block gap',`data-id="${x.id}" data-index="${i}"`):''}</div>`).join('')||empty('暂无认款记录','客户付款后，可提交凭证交财务复核。')}${x.status==='已确认'&&available(x)>0?`${section(editing?'补充原认款申请':'登记认款')}<form data-form="claim" data-claim-index="${editing?env.route().claimIndex:''}">${errors()}${editing?`<div class="hint">补充 ${e(prior.reference)}，保留原退回记录；无需客户重复付款。</div>`:''}${field('认领金额（元）','amount',editing?prior.amount:'','number',`min="0.01" max="${available(x)}" step="0.01"`)}${field('付款人姓名','payer',editing?prior.payer:customer()?.name)}${field('银行交易流水号','reference',editing?prior.reference:'')}${field('付款日期','date',prior?.date||M.TODAY,'date',`max="${M.TODAY}"`)}${field('付款凭证','proof','','file','accept="image/*,.pdf"')}${prior?.proof?`<p class="small">已保留原凭证：${e(prior.proof)}</p>`:''}${textarea('代付关系说明（非本人付款时必填）','relation',prior?.relation||'')}<div class="hint">提交后为待复核，由财务核对到账；不直接增加已确认收款。</div>${btn(editing?'补充并重新提交':'提交财务复核','submit-form','primary block gap')}</form>`:`<div class="hint">${x.status!=='已确认'?'本单尚未确认，当前仅可查看认款记录。':'当前无可新认领金额，请查看已有认款结果。'}</div>`}`;}
  function travelers(){const x=order();return back('游客资料')+context(x)+env.travelersBody(x);}
  function travel(){const x=order();return back('出行资料')+context(x)+env.travelBody(x);}
  function aftersale(){const x=order(),waiting=x.aftersales.some(a=>a.status==='待审核');return back('售后办理')+context(x)+`<div class="card card-pad">${facts([['原出发日期',e(x.date)],['订单金额',M.money(x.total)],['已确认收款',M.money(x.paid)]])}</div>${section('售后记录')}${x.aftersales.map(a=>`<div class="card card-pad"><div class="row"><h3>${e(a.type)}申请</h3>${badge(a.status,'orange')}</div><p class="small">${e(a.id)}</p><p>${e(a.reason)}</p>${facts([[a.type==='改期'?'期望日期':'客户退款诉求',a.type==='改期'?e(a.date):M.money(a.amount)],['当前办理','待业务审核']])}<div class="hint">尚未改变原订单、资源或实收；退款须经审核后由财务执行。</div></div>`).join('')||empty('暂无售后申请','可在下方填写本单改期或退订诉求。')}${x.status==='已确认'&&!waiting?`${section('发起售后')}<form data-form="aftersale">${errors()}${select('售后诉求','type',['改期','退订'],'改期')}<div id="aftersale-fields">${field('期望出发日期','date','','date',`min="${M.TODAY}"`)}</div>${textarea('申请原因及客户确认依据','reason','','placeholder="说明客户诉求及已沟通内容"')}<div class="hint">申请不改变原订单，不自动退款。业务审核后按实际结果继续办理。</div>${btn('提交售后申请','submit-form','primary block gap')}</form>`:`<div class="hint">${waiting?'已有待审核申请，请等待业务审核结果，避免重复提交。':'本单尚未确认，请先查看业务确认结果。'}</div>`}`;}
  function contract(){const x=order(),missing=x.travelers.some(t=>M.travelerErrors(t,x.date).length);return back('合同办理')+context(x)+`<div class="receipt"><div class="row"><h2>${contractName(x)}</h2>${badge(x.contract,x.contract==='已签署'?'green':'orange')}</div>${facts([['签约公司',e(x.company)],['签署联系人',e(customer()?.name)],['合同金额',M.money(x.total)],['覆盖游客',x.travelers.map(t=>e(t.name||'待补姓名')).join('、')],['附件','行程安排、费用及游客名单']])}${btn('预览合同与附件','order-page','secondary block gap',`data-page="contract-preview" data-id="${x.id}"`)}</div>${x.status!=='已确认'?'<div class="hint warn">订单尚未确认，暂不能发起签署。</div>':x.contract==='未生成'?missing?`<div class="hint warn">游客必要资料尚未齐全，请先补齐后发起签署。</div>${btn('补充游客资料','order-page','primary block gap',`data-id="${x.id}" data-page="order-travelers"`)}`:`<form data-form="contract">${errors()}<label class="check"><input type="checkbox" name="checked">已核对签约公司、签署人、游客名单、订单金额及行程附件。</label>${btn('发起签署','submit-form','primary block')}</form>`:`<div class="card card-pad"><h3>签署进度</h3><p>${x.contract==='已签署'?'本单已签署，合同归档和备案由合同岗位承接。':'已发起签署，等待客户完成。'}</p><p class="small">销售不能代客户签署；签署结果与收款状态分别记录。</p></div>`}`;}
  function contractPreview(){const x=order(),p=product(x);return back('合同与附件')+context(x)+`<div class="card card-pad"><h2>${contractName(x)}</h2><p class="small">订单内容核对 · 原型示例</p>${facts([['旅行社',e(x.company)],['旅游产品',e(x.title)],['出发日期',e(x.date)],['合同金额',M.money(x.total)],['游客名单',x.travelers.map(t=>e(t.name||'待补姓名')).join('、')]])}<div class="hint">此处供核对订单和附件，正式合同以合同岗位审核后的完整文本为准。</div></div>${section('费用及退改附件')}<div class="card card-pad">${p?`<h3>费用包含</h3><p>${e(p.includes)}</p><h3>费用不含</h3><p>${e(p.excludes)}</p><h3>退改约定</h3><p>${e(p.policy)}</p>`:'<p>当前订单未关联可预览的产品费用附件，请由合同岗位补齐后核对。</p>'}</div>${section('行程附件')}${p?.itinerary?.length?dayList({days:p.itinerary}):empty('行程附件待补充','请核对本单已确认的行程版本。')}`;}
  return {screens:{order:detail,payment,claim:payment,contract,'contract-preview':contractPreview,'order-travelers':travelers,'order-travel':travel,'order-aftersale':aftersale,aftersale}};
};
