(function(){
'use strict';const role=location.pathname.endsWith('finance-supplier-bills.html')?'bill':'payable',M=window.PayableLedgerModel,S=M.createSession(window.PayableLedgerSeeds,role),root=document.querySelector('[data-payable-ledger]');if(!root)return;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),money=(v,c='CNY')=>v==null?'待核对':(c==='CNY'?'¥':c+' ')+Number(v).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2}),line=(a,b='')=>'<strong class="pl-line">'+esc(a)+'</strong>'+(b?'<span class="pl-muted pl-line">'+esc(b)+'</span>':''),tag=s=>'<span class="tag tag-'+(['已核验','已确认','已结清'].includes(s)?'green':s==='已关闭'?'gray':s==='已退回'?'red':'orange')+'">'+esc(s)+'</span>',section=t=>'<div class="drawer-section-head"><h3 class="drawer-section-title">'+esc(t)+'</h3></div>',facts=xs=>'<dl class="pl-facts">'+xs.map(([k,v])=>'<div><dt>'+esc(k)+'</dt><dd>'+esc(v)+'</dd></div>').join('')+'</dl>',button=(a,t,primary=false,more='')=>'<button class="btn '+(primary?'btn-primary':'btn-secondary')+'" type="button" data-pl-action="'+a+'" '+more+'>'+esc(t)+'</button>';
const list=()=>role==='bill'?S.bills():S.payables(),options=(items,label)=>'<option value="">'+label+'</option>'+items.map(v=>'<option>'+esc(v)+'</option>').join(''),all=list(),statuses=role==='bill'?['待核验','已核验','已退回','已关闭']:['待确认','已确认','已结清','已退回','已关闭'];
root.innerHTML='<section class="list-surface pl-surface"><section class="filter-card filter-card-compact list-surface-filter"><div class="filter-row"><div class="filter-item"><input class="form-control" id="plSearch" type="search" aria-label="单据、供应商或费用" placeholder="单据 / 供应商 / 团期 / 费用"></div><div class="filter-item-sm"><select id="plState" aria-label="主状态">'+options(statuses,'全部状态')+'</select></div><div class="filter-item-sm"><select id="plCompany" aria-label="公司">'+options([...new Set(all.map(x=>x.company))],'全部公司')+'</select></div><div class="filter-item-sm"><select id="plCurrency" aria-label="币种">'+options([...new Set(all.map(x=>x.currency))],'全部币种')+'</select></div><div class="filter-item-sm"><label class="sr-only" for="plDate">'+(role==='bill'?'账单日期截至':'到期日期截至')+'</label><input id="plDate" type="date" title="'+(role==='bill'?'账单日期截至':'到期日期截至')+'"></div><div class="filter-actions">'+button('search','搜索')+button('reset','重置')+'</div></div><div class="list-surface-filter-actions list-filter-pinned-actions">'+(role==='bill'?button('supplement','补录账单'): '')+button('export','导出')+'</div></section><div class="table-wrap list-surface-table"><table class="pl-table '+(role==='bill'?'pl-bills':'pl-payables')+'"><colgroup>'+Array(role==='bill'?7:8).fill('<col>').join('')+'</colgroup><thead><tr>'+(role==='bill'?['账单／来源','供应商／公司','业务确认依据','账单金额','业务核对金额','核验状态','操作']:['应付单／来源','供应商／费用','应付金额','已抵清','未结清／可申请','到期日','应付状态','操作']).map((v,i,a)=>'<th'+(i===a.length-1?' class="sticky-action"':'')+'>'+v+'</th>').join('')+'</tr></thead><tbody id="'+(role==='bill'?'billRows':'payableRows')+'"></tbody></table></div><div class="pagination" id="plCount"></div></section><div class="pl-toast sf-toast" role="status" hidden></div>';
const host=document.createElement('div');host.className='pl-app';host.innerHTML='<div class="modal-overlay drawer-overlay pl-overlay sf-overlay" hidden><div class="modal drawer-modal pl-drawer" role="dialog" aria-modal="true" aria-labelledby="plTitle" tabindex="-1"><div class="modal-header"><div class="modal-title" id="plTitle"></div><button class="modal-close" data-pl-action="close" aria-label="关闭">×</button></div><div class="modal-body pl-body sf-body"></div><div class="modal-footer pl-footer sf-footer"></div></div></div><div class="modal-overlay pl-discard sf-confirm" hidden><div class="modal modal-sm modal-confirm" role="alertdialog" aria-modal="true" aria-label="放弃修改"><div class="modal-header"><div class="modal-title">放弃修改</div></div><div class="modal-body">本次填写尚未保存，确认放弃？</div><div class="modal-footer">'+button('keep','继续填写')+button('discard','放弃修改',true)+'</div></div></div>';document.body.append(host);
const overlay=host.querySelector('.pl-overlay'),body=host.querySelector('.pl-body'),footer=host.querySelector('.pl-footer'),discard=host.querySelector('.pl-discard');let active=null,dirty=false,focus,pending=null,mode='detail';
let toastTimer;function toast(t,sticky=false){const n=root.querySelector('.pl-toast');clearTimeout(toastTimer);n.textContent=t;n.hidden=false;if(!sticky)toastTimer=setTimeout(()=>n.hidden=true,2400);}
function visible(){const q=root.querySelector('#plSearch').value.trim().toLowerCase(),state=root.querySelector('#plState').value,company=root.querySelector('#plCompany').value,currency=root.querySelector('#plCurrency').value,date=root.querySelector('#plDate').value;return list().filter(r=>(!q||JSON.stringify(r).toLowerCase().includes(q))&&(!state||(r.displayState||r.state)===state)&&(!company||company===r.company)&&(!currency||currency===r.currency)&&(!date||(role==='bill'?r.date:r.due)<=date)).sort((a,b)=>Number(['待核验','待确认'].includes(b.state))-Number(['待核验','待确认'].includes(a.state))||(a.due||a.date).localeCompare(b.due||b.date));}
function render(){const rows=visible();root.querySelector('tbody').innerHTML=rows.map(r=>{const t=r.totals,st=r.displayState||r.state,cells=role==='bill'?[line(r.id,r.source),line(r.supplier,r.company+' · '+r.currency),line(r.confirmationNo||'业务确认待补',r.tour),money(r.amount,r.currency),money(r.agreed,r.currency),tag(st)]:[line(r.id,r.source),line(r.supplier,r.company+' · '+r.item),money(t.confirmed,r.currency),money(t.settled,r.currency),line(money(t.remaining,r.currency),t.overpaid>0?'多付应退 '+money(t.overpaid,r.currency):'可申请 '+money(t.available,r.currency)),esc(r.due),tag(st)];return '<tr data-pl-id="'+esc(r.id)+'"'+(r.statement?' data-sf-id="'+esc(r.statement)+'"':'')+'>'+cells.map(c=>'<td>'+c+'</td>').join('')+'<td class="sticky-action"><div class="table-action"><button type="button" class="table-action-primary" data-open-detail data-pl-open="'+esc(r.id)+'">'+(r.state==='待核验'?'核验':r.state==='待确认'?'确认应付':'详情')+'</button></div></td></tr>';}).join('')||'<tr><td colspan="'+(role==='bill'?7:8)+'" class="pl-empty">没有符合条件的记录</td></tr>';root.querySelector('#plCount').textContent='共 '+rows.length+' 条';}
function title(t){const n=host.querySelector('#plTitle');n.textContent=t;n.dataset.drawerTitleLocked=t;}
function show(){focus=document.activeElement;overlay.hidden=false;requestAnimationFrame(()=>{overlay.classList.add('show');overlay.querySelector('[role="dialog"]').focus();});body.scrollTop=0;}
function leave(callback){if(dirty){pending=callback;discard.hidden=false;discard.classList.add('show');discard.querySelector('button').focus();return;}callback();}
function close(){leave(()=>{overlay.hidden=true;overlay.classList.remove('show');focus?.focus();});}
function issue(err){const n=body.querySelector('.pl-error');n.textContent=err.message;n.hidden=false;n.scrollIntoView({block:'nearest'});}
const history=r=>section('处理记录')+(r.history.length?r.history.map(h=>'<div class="pl-record"><strong>'+esc(h.action)+'</strong><p>'+esc(h.basis)+'</p><span class="pl-muted">'+esc(h.actor+' · '+h.date)+'</span></div>').join(''):'<p class="pl-muted">暂无本页办理记录</p>');
function links(r){const qs=r.statement?'statementNo='+encodeURIComponent(r.statement)+'&revision='+r.revision:'';let html='<nav class="pl-related sf-related">';if(r.statement)html+='<a href="../tour/supplier-reconciliation.html?'+qs+'">原供应商对账</a>';else html+='<a href="../tour/fulfillment-cost.html?businessNo='+encodeURIComponent(r.tour)+'&costNo='+encodeURIComponent(r.costId)+'">业务成本依据</a>';if(role==='bill'&&r.payableId)html+='<a href="finance-payable.html?payableNo='+encodeURIComponent(r.payableId)+'">原应付记录</a>';if(role==='payable'){r.billIds.forEach(id=>html+='<a href="finance-supplier-bills.html?billNo='+encodeURIComponent(id)+'">账单 '+esc(id)+'</a>');html+='<a href="finance-prepayment-offset.html'+(qs?'?'+qs:'')+'">预付冲抵</a><a href="finance-payment-management.html'+(qs?'?'+qs:'')+'">付款记录</a><a href="finance-invoice.html'+(qs?'?'+qs:'')+'">发票材料</a>';}return html+'</nav>';}
function table(headers,rows){return '<div class="table-wrap pl-detail-table"><table><thead><tr>'+headers.map(x=>'<th>'+esc(x)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(xs=>'<tr>'+xs.map(x=>'<td>'+x+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';}
function draw(){dirty=false;const r=role==='bill'?S.getBill(active):S.getPayable(active);title(role==='bill'?'账单核验':'应付核对');let actions='',html='<div class="pl-error rec-error" role="alert" hidden></div><section class="drawer-object-card"><div class="drawer-object-main"><div><strong class="drawer-object-title">'+esc(r.id+' / '+r.supplier)+'</strong><p class="pl-muted">'+esc(r.company+' · '+r.item+' · '+r.tour)+'</p></div>'+tag(r.displayState||r.state)+'</div>';
 if(role==='bill'){
 html+=facts([['供应商账单',money(r.amount,r.currency)],['业务核对金额',money(r.agreed,r.currency)],['金额差异',money(r.agreed==null?null:r.amount-r.agreed,r.currency)]])+'</section>'+section('业务与材料依据')+facts([['对方账单号',r.counterNo],['我方经办',r.handler],['业务确认',r.businessConfirmed?'已确认':'待业务确认'],['确认依据',r.confirmationNo||'待补齐'],['账单附件',r.file||'待补齐'],['原应付',r.payableId||'尚未形成']])+(r.statement?'<p>'+esc(r.statement+' · 第 '+r.revision+' 版')+'</p>':'')+(r.discountEvidence?facts([['已确认优惠依据',r.discountEvidence]]):'')+(r.returnReason?facts([['退回原因',r.returnReason]]):'');
 if(r.state==='待核验'){html+=section('本次核验')+'<form class="pl-form sf-form"><label class="pl-full">核验结果<select class="form-control" name="action"><option value="pass">核验通过</option><option value="return">退回业务补充</option></select></label><label class="pl-full"><input type="checkbox" name="materialChecked"> 已核对本版业务确认及账单材料</label><label class="pl-full"><input type="checkbox" name="scopeChecked"> 已核对公司、供应商及费用范围，无重复报账</label><label class="pl-full">核验依据／退回原因<textarea class="form-control" name="basis" rows="3"></textarea></label></form>';if(!r.ready)html+='<div class="pl-gap">'+esc(!r.businessConfirmed?'业务尚未确认最终金额':!r.file?'账单附件缺失':'账单金额差异缺确认依据')+'</div>';actions=button('review','核验通过',true)+(r.duplicateOf?button('close-bill','关闭重复账单'):'');}
 }else{
 const t=r.totals;html+=facts([[r.state==='待确认'?'待确认金额':'确认金额',money(t.confirmed,r.currency)],['未结清',money(t.remaining,r.currency)],['可申请',money(t.available,r.currency)]])+'</section>'+section('欠款确认依据')+facts([['费用编号',r.costId],['来源',r.source+' / '+r.sourceNo],['业务经办',r.handler],['确认依据',r.confirmationNo||'待补齐'],['业务确认',r.sourceConfirmed?'已确认':'待业务确认'],['到期日',r.due]])+(r.statement?'<p>'+esc(r.statement+' · 第 '+r.revision+' 版')+'</p>':'')+(r.gaps.length?'<div class="pl-gap">'+esc(r.gaps.join('；'))+'</div>':'')+section('余额核对')+facts([['原应付',money(t.original,r.currency)],['有效调整',money(t.adjustment,r.currency)],['预付已冲抵',money(t.offset,r.currency)],['原付款有效抵清',money(t.allocated,r.currency)],['退回抵清转回',money(t.returned,r.currency)],['申请／付款中占用',money(t.processing,r.currency)],['多付应退',money(t.overpaid,r.currency)],['占用超出未结清',money(t.overOccupied,r.currency)]]);
 if(r.offsets.length)html+=table(['冲抵单','原预付','已冲抵'],r.offsets.map(x=>[esc(x.id),esc(x.prepay),money(x.amount,r.currency)]));
 if(r.payments.length)html+=table(['原付款','原实付','有效抵清应付','银行交易号'],r.payments.map(x=>[esc(x.id),money(x.amount,r.currency),money(x.allocated,r.currency),esc(x.reference)]));
 if(r.processing.length)html+=table(['付款申请／付款单','占用金额','办理状态'],r.processing.map(x=>[esc(x.id),money(x.amount,r.currency),esc(x.state)]));
 if(r.state==='待确认'){html+=section('本次确认')+'<form class="pl-form sf-form"><label class="pl-full"><input type="checkbox" name="responsibilityChecked"> 已核对欠款公司、费用范围及原付款／冲抵记录</label><label class="pl-full">确认依据／退回原因<textarea name="basis" class="form-control" rows="3"></textarea></label></form>';actions=button('return-source','退回业务')+button('confirm','确认应付',true);}
 if(r.adjustments.length)html+=section('业务调整')+r.adjustments.map(x=>'<div class="pl-record"><strong>'+esc(x.id)+' · '+money(x.delta,r.currency)+'</strong><p>'+esc(x.evidence||'业务确认待补')+'</p><span>'+esc(x.applied?'已登记':x.confirmed?'待财务登记':'待业务确认')+'</span>'+(!x.applied?'<div class="pl-inline"><label>核对依据<textarea class="form-control" data-pl-adjust-basis="'+esc(x.id)+'" rows="2"></textarea></label>'+button('adjust','登记调整',false,'data-adjustment="'+esc(x.id)+'"')+'</div>':'')+'</div>').join('');
 if(r.returns.length)html+=section('退回与原款')+r.returns.map(x=>'<div class="pl-record"><strong>'+esc(x.id+' · '+x.kind)+' · '+money(x.received,r.currency)+'</strong>'+facts([['原付款',x.paymentId||'待匹配'],['到账流水',x.receiptNo||'待核对'],['应付余额处理',x.applied?(x.allocation?'已转回抵清 '+money(x.allocation,r.currency):'未抵清原款退回，应付不变'):!x.matched?'待资金岗匹配原款':'待核对原款影响']])+(!x.applied&&x.matched?'<div class="pl-inline"><label>原款核对依据<textarea class="form-control" data-pl-return-basis="'+esc(x.id)+'" rows="2"></textarea></label>'+button('apply-return','核对退回',false,'data-return="'+esc(x.id)+'"')+'</div>':'')+'</div>').join('');
 }
 html+=section('关联单据')+links(r)+history(r);body.innerHTML=html;footer.innerHTML=button('close','关闭')+actions;body.scrollTop=0;
}
function open(id){active=id;mode='detail';draw();show();}
function supplement(){mode='supplement';dirty=false;title('补录账单');body.innerHTML='<div class="pl-error" role="alert" hidden></div><form class="pl-form"><label class="pl-full">费用依据<select name="payableId" class="form-control">'+S.payables().filter(p=>p.state!=='已关闭').map(p=>'<option value="'+esc(p.id)+'">'+esc(p.company+' / '+p.supplier+' / '+p.costId+' / '+p.currency)+'</option>').join('')+'</select></label><label>对方账单号<input name="counterNo" class="form-control"></label><label>账单金额（原币）<input name="amount" type="number" min="0.01" step="0.01" class="form-control"></label><label>业务经办<input name="handler" class="form-control"></label><label>账单文件<input name="file" type="file" accept=".pdf,.xlsx,.xls,.csv,.png,.jpg,.jpeg" class="form-control"></label><label class="pl-full">补录依据<textarea name="basis" class="form-control" rows="3"></textarea></label></form>';footer.innerHTML=button('close','取消')+button('save-supplement','保存待核验',true);show();}
function exportRows(){const headers=role==='bill'?['账单','供应商','公司','币种','账单金额','业务核对金额','状态']:['应付','供应商','公司','币种','应付金额','已抵清','未结清','占用','可申请','状态'];const rows=visible().map(r=>role==='bill'?[r.id,r.supplier,r.company,r.currency,r.amount,r.agreed??'待核对',r.state]:[r.id,r.supplier,r.company,r.currency,r.totals.confirmed,r.totals.settled,r.totals.remaining??'待核对',r.totals.processing,r.totals.available,r.displayState]);const url=URL.createObjectURL(new Blob(['\ufeff'+[headers,...rows].map(xs=>xs.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=(role==='bill'?'账单核验':'应付管理')+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
root.addEventListener('click',e=>{const b=e.target.closest('[data-pl-open]');if(b){open(b.dataset.plOpen);return;}const a=e.target.closest('[data-pl-action]')?.dataset.plAction;if(a==='search')render();if(a==='reset'){root.querySelectorAll('input,select').forEach(x=>x.value='');render();}if(a==='supplement')supplement();if(a==='export')exportRows();});root.querySelector('#plSearch').addEventListener('keydown',e=>{if(e.key==='Enter')render();});root.querySelectorAll('select').forEach(x=>x.addEventListener('change',render));
host.addEventListener('input',()=>dirty=true);host.addEventListener('change',e=>{dirty=true;if(e.target.name==='action')footer.querySelector('[data-pl-action="review"]').textContent=e.target.value==='return'?'退回业务':'核验通过';});
host.addEventListener('click',e=>{const a=e.target.closest('[data-pl-action]')?.dataset.plAction;if(!a){const link=e.target.closest('a');if(link&&dirty){e.preventDefault();leave(()=>{dirty=false;location.href=link.href;});}if(e.target===overlay)close();return;}e.stopImmediatePropagation();if(a==='close'){close();return;}if(a==='keep'){discard.hidden=true;discard.classList.remove('show');pending=null;return;}if(a==='discard'){dirty=false;discard.hidden=true;discard.classList.remove('show');pending?.();pending=null;return;}try{if(a==='save-supplement'){const form=body.querySelector('form'),data=Object.fromEntries(new FormData(form));if(!data.file?.name)throw Error('请上传账单材料');if(data.file.size>10*1024*1024)throw Error('附件不能超过10MB');active=S.supplement({...data,file:data.file.name}).id;mode='detail';}else{const r=role==='bill'?S.getBill(active):S.getPayable(active),form=body.querySelector('form'),data=form?Object.fromEntries(new FormData(form)):{};if(a==='review')S.reviewBill(active,r.version,{...data,materialChecked:!!data.materialChecked,scopeChecked:!!data.scopeChecked});if(a==='close-bill')S.closeBill(active,r.version,data.basis);if(a==='confirm')S.confirm(active,r.version,{...data,responsibilityChecked:!!data.responsibilityChecked});if(a==='return-source')S.returnSource(active,r.version,data.basis);if(a==='adjust'){const id=e.target.closest('[data-adjustment]').dataset.adjustment;S.adjust(active,r.version,id,body.querySelector('[data-pl-adjust-basis="'+id+'"]').value);}if(a==='apply-return'){const id=e.target.closest('[data-return]').dataset.return;S.applyReturn(active,r.version,id,body.querySelector('[data-pl-return-basis="'+id+'"]').value);}}render();draw();toast('本次核对已保存');}catch(err){issue(err);}},true);
host.addEventListener('keydown',e=>{if(e.key==='Escape'){e.stopPropagation();if(!discard.hidden){discard.hidden=true;discard.classList.remove('show');pending=null;}else close();}if(e.key==='Tab'){const scope=discard.hidden?overlay:discard,ns=Array.from(scope.querySelectorAll('button,input,select,textarea,a')).filter(n=>!n.disabled&&n.getClientRects().length),first=ns[0],last=ns.at(-1);if(e.shiftKey&&(document.activeElement===first||!ns.includes(document.activeElement))){e.preventDefault();last?.focus();}else if(!e.shiftKey&&(document.activeElement===last||!ns.includes(document.activeElement))){e.preventDefault();first?.focus();}}});
render();const q=new URLSearchParams(location.search),id=q.get(role==='bill'?'billNo':'payableNo'),statement=q.get('statementNo');if(id||statement){const r=list().find(x=>id?(x.id===id||(x.aliases||[]).includes(id)):x.statement===statement);if(!r)toast('未找到本单记录，请核对原单号',true);else if(q.get('revision')&&q.get('revision')!==String(r.revision))toast('对账版本与本页依据不一致，请核对最新版本',true);else open(r.id);}
})();
