const {test}=require('node:test');
const assert=require('node:assert/strict');
const M=require('../src/model.js');
const fixture=()=>{const s=M.seed(),d=M.demand(s),p=M.plan(d);return {s,d,p};};
const standard=()=>({kind:'standard',productId:'p1',date:'2026-11-15',customerId:'c1',contact:'李梅',phone:'13800000001',adults:2,children:1,childAge:8,childBed:'不占床',accept:true});
test('标准家庭订单按成人、儿童与占床分别计算',()=>{assert.equal(M.standardTotal(standard()),26400);assert.equal(M.standardTotal({...standard(),childBed:'占床'}),27200);});
test('售罄日期禁止提交',()=>{const {s}=fixture();assert.throws(()=>M.submitBooking(s,{...standard(),date:'2026-11-22'}),/余位不足/);assert.equal(s.orders.length,2);});
test('超出余位禁止提交',()=>assert.throws(()=>M.submitBooking(M.seed(),{...standard(),adults:13}),/余位不足/));
test('儿童缺年龄或规格禁止提交',()=>{const s=M.seed();assert.throws(()=>M.submitBooking(s,{...standard(),childAge:''}),/儿童/);assert.throws(()=>M.submitBooking(s,{...standard(),childBed:''}),/儿童/);});
test('标准提交形成已确认订单，实收仍为零',()=>{const o=M.submitBooking(M.seed(),standard());assert.equal(o.status,'已确认');assert.equal(o.paid,0);assert.equal(o.total,26400);});
test('二次确认团期只能进入待确认',()=>{const o=M.submitBooking(M.seed(),{...standard(),date:'2026-12-06'});assert.equal(o.status,'待确认');assert.equal(o.resource,'待确认');});
test('方案修改保留已确认版，清除新版报价与确认',()=>{const {s,d,p}=fixture();M.adoptQuote(d,p,M.quoteFor(d,p));M.confirmPlan(d,p,'客户微信确认');const original=M.clone(p);const updated=M.revise(s,d.id);assert.deepEqual(p,original);assert.equal(updated.quote,null);assert.equal(updated.confirmation,null);assert.equal(updated.version,3);});
test('同一客户不同需求和跨客户不串方案',()=>{const {s}=fixture();M.revise(s,'d1');assert.equal(M.demand(s,'d4').plans.length,0);assert.equal(M.demand(s,'d5').plans.length,0);});
test('日期、儿童年龄缺失时先补需求',()=>{const {s}=fixture();assert.deepEqual(M.missing(M.demand(s,'d5')),['出发日期','儿童年龄']);assert.throws(()=>M.revise(s,'d5'),/补充/);});
test('过期报价不可采用',()=>{const {d,p}=fixture();assert.throws(()=>M.adoptQuote(d,p,M.quoteFor(d,p,true)),/过期/);assert.equal(p.quote,null);});
test('报价必须对应版本和人数',()=>{const {d,p}=fixture();assert.throws(()=>M.adoptQuote(d,p,{...M.quoteFor(d,p),version:1}),/不一致/);d.adults=3;assert.equal(M.quoteFor(d,p),null);});
test('无报价或无客户依据不能确认',()=>{const {d,p}=fixture();assert.throws(()=>M.confirmPlan(d,p,'确认'),/有效报价/);M.adoptQuote(d,p,M.quoteFor(d,p));assert.throws(()=>M.confirmPlan(d,p,''),/依据/);});
test('定制开单进入项目待确认，重复提交与串客户拦截',()=>{const {s,d,p}=fixture();M.adoptQuote(d,p,M.quoteFor(d,p));M.confirmPlan(d,p,'微信确认V2');const b={...standard(),kind:'custom',demandId:d.id,version:p.version};assert.throws(()=>M.submitBooking(s,{...b,customerId:'c2'}),/客户或方案/);const o=M.submitBooking(s,b);assert.equal(o.status,'待确认');assert.equal(o.total,29600);assert.equal(p.orderId,o.id);assert.throws(()=>M.submitBooking(s,b),/已转订单/);});
test('认款提交仅增加待复核，不增加实收',()=>{const {s}=fixture(),o=s.orders[0];M.submitClaim(o,{amount:20000,payer:'张伟',customerName:'张建国',reference:'BANK200',proof:'付款凭证.png',relation:'父子代付'});assert.equal(o.paid,10000);assert.equal(o.claims.at(-1).status,'待复核');});
test('认款超额、重复流水与代付缺关系均拦截',()=>{const o=M.seed().orders[0],f={amount:20000,payer:'张伟',customerName:'张建国',reference:'B1',proof:'1.png',relation:'父子'};assert.throws(()=>M.submitClaim(o,{...f,amount:39000}),/金额/);assert.throws(()=>M.submitClaim(o,{...f,relation:''}),/代付/);M.submitClaim(o,f);assert.throws(()=>M.submitClaim(o,f),/金额|流水/);});
test('售后申请不改变原订单金额、日期与实收',()=>{const o=M.seed().orders[0];M.submitAftersale(o,{type:'退订',amount:5000,reason:'客户申请退订'});assert.equal(o.total,48000);assert.equal(o.paid,10000);assert.equal(o.status,'已确认');assert.equal(o.aftersales[0].status,'待审核');assert.throws(()=>M.submitAftersale(o,{type:'退订',amount:5000,reason:'重复'}),/已有/);});
test('超实收退款诉求不能提交',()=>assert.throws(()=>M.submitAftersale(M.seed().orders[0],{type:'退订',amount:11000,reason:'退订'}),/不超过/));
test('游客缺项与过期证件阻断',()=>{assert.ok(M.travelerErrors({name:'李梅'},'2026-11-15').length);assert.ok(M.travelerErrors({name:'李梅',english:'LI/MEI',passport:'E00001',birth:'1980-01-01',expiry:'2026-10-10'},'2026-11-15').length);});
test('标准开单草稿不能重复提交',()=>{const s=M.seed(),b={...standard(),bookingId:'B1'};M.submitBooking(s,b);assert.throws(()=>M.submitBooking(s,b),/已经提交/);});
test('修改需求后不能用旧报价直接确认或开单',()=>{const {s,d,p}=fixture();M.adoptQuote(d,p,M.quoteFor(d,p));d.date='2026-11-22';assert.equal(M.plan(d),undefined);assert.throws(()=>M.confirmPlan(d,p,'客户确认'),/有效报价/);});
